/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.anblicks.pdca.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AstraPdca_CompanyData service. Represents a row in the &quot;pdca_astrapdca_companydata&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.astra.anblicks.pdca.model.impl.AstraPdca_CompanyDataModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.astra.anblicks.pdca.model.impl.AstraPdca_CompanyDataImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AstraPdca_CompanyData
 * @see com.astra.anblicks.pdca.model.impl.AstraPdca_CompanyDataImpl
 * @see com.astra.anblicks.pdca.model.impl.AstraPdca_CompanyDataModelImpl
 * @generated
 */
@ProviderType
public interface AstraPdca_CompanyDataModel extends BaseModel<AstraPdca_CompanyData>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a astra pdca_ company data model instance should use the {@link AstraPdca_CompanyData} interface instead.
	 */

	/**
	 * Returns the primary key of this astra pdca_ company data.
	 *
	 * @return the primary key of this astra pdca_ company data
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this astra pdca_ company data.
	 *
	 * @param primaryKey the primary key of this astra pdca_ company data
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the company ID of this astra pdca_ company data.
	 *
	 * @return the company ID of this astra pdca_ company data
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this astra pdca_ company data.
	 *
	 * @param companyId the company ID of this astra pdca_ company data
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the company code of this astra pdca_ company data.
	 *
	 * @return the company code of this astra pdca_ company data
	 */
	@AutoEscape
	public String getCompanyCode();

	/**
	 * Sets the company code of this astra pdca_ company data.
	 *
	 * @param CompanyCode the company code of this astra pdca_ company data
	 */
	public void setCompanyCode(String CompanyCode);

	/**
	 * Returns the company name of this astra pdca_ company data.
	 *
	 * @return the company name of this astra pdca_ company data
	 */
	@AutoEscape
	public String getCompanyName();

	/**
	 * Sets the company name of this astra pdca_ company data.
	 *
	 * @param CompanyName the company name of this astra pdca_ company data
	 */
	public void setCompanyName(String CompanyName);

	/**
	 * Returns the group name of this astra pdca_ company data.
	 *
	 * @return the group name of this astra pdca_ company data
	 */
	@AutoEscape
	public String getGroupName();

	/**
	 * Sets the group name of this astra pdca_ company data.
	 *
	 * @param GroupName the group name of this astra pdca_ company data
	 */
	public void setGroupName(String GroupName);

	/**
	 * Returns the dic of this astra pdca_ company data.
	 *
	 * @return the dic of this astra pdca_ company data
	 */
	@AutoEscape
	public String getDIC();

	/**
	 * Sets the dic of this astra pdca_ company data.
	 *
	 * @param DIC the dic of this astra pdca_ company data
	 */
	public void setDIC(String DIC);

	/**
	 * Returns the dicinitial of this astra pdca_ company data.
	 *
	 * @return the dicinitial of this astra pdca_ company data
	 */
	@AutoEscape
	public String getDICINITIAL();

	/**
	 * Sets the dicinitial of this astra pdca_ company data.
	 *
	 * @param DICINITIAL the dicinitial of this astra pdca_ company data
	 */
	public void setDICINITIAL(String DICINITIAL);

	/**
	 * Returns the leftup of this astra pdca_ company data.
	 *
	 * @return the leftup of this astra pdca_ company data
	 */
	@AutoEscape
	public String getLEFTUP();

	/**
	 * Sets the leftup of this astra pdca_ company data.
	 *
	 * @param LEFTUP the leftup of this astra pdca_ company data
	 */
	public void setLEFTUP(String LEFTUP);

	/**
	 * Returns the leftuptitle of this astra pdca_ company data.
	 *
	 * @return the leftuptitle of this astra pdca_ company data
	 */
	@AutoEscape
	public String getLEFTUPTITLE();

	/**
	 * Sets the leftuptitle of this astra pdca_ company data.
	 *
	 * @param LEFTUPTITLE the leftuptitle of this astra pdca_ company data
	 */
	public void setLEFTUPTITLE(String LEFTUPTITLE);

	/**
	 * Returns the leftupcompany of this astra pdca_ company data.
	 *
	 * @return the leftupcompany of this astra pdca_ company data
	 */
	@AutoEscape
	public String getLEFTUPCOMPANY();

	/**
	 * Sets the leftupcompany of this astra pdca_ company data.
	 *
	 * @param LEFTUPCOMPANY the leftupcompany of this astra pdca_ company data
	 */
	public void setLEFTUPCOMPANY(String LEFTUPCOMPANY);

	/**
	 * Returns the leftbottom of this astra pdca_ company data.
	 *
	 * @return the leftbottom of this astra pdca_ company data
	 */
	@AutoEscape
	public String getLEFTBOTTOM();

	/**
	 * Sets the leftbottom of this astra pdca_ company data.
	 *
	 * @param LEFTBOTTOM the leftbottom of this astra pdca_ company data
	 */
	public void setLEFTBOTTOM(String LEFTBOTTOM);

	/**
	 * Returns the leftbottomtitle of this astra pdca_ company data.
	 *
	 * @return the leftbottomtitle of this astra pdca_ company data
	 */
	@AutoEscape
	public String getLEFTBOTTOMTITLE();

	/**
	 * Sets the leftbottomtitle of this astra pdca_ company data.
	 *
	 * @param LEFTBOTTOMTITLE the leftbottomtitle of this astra pdca_ company data
	 */
	public void setLEFTBOTTOMTITLE(String LEFTBOTTOMTITLE);

	/**
	 * Returns the leftbottomcompany of this astra pdca_ company data.
	 *
	 * @return the leftbottomcompany of this astra pdca_ company data
	 */
	@AutoEscape
	public String getLEFTBOTTOMCOMPANY();

	/**
	 * Sets the leftbottomcompany of this astra pdca_ company data.
	 *
	 * @param LEFTBOTTOMCOMPANY the leftbottomcompany of this astra pdca_ company data
	 */
	public void setLEFTBOTTOMCOMPANY(String LEFTBOTTOMCOMPANY);

	/**
	 * Returns the midup of this astra pdca_ company data.
	 *
	 * @return the midup of this astra pdca_ company data
	 */
	@AutoEscape
	public String getMIDUP();

	/**
	 * Sets the midup of this astra pdca_ company data.
	 *
	 * @param MIDUP the midup of this astra pdca_ company data
	 */
	public void setMIDUP(String MIDUP);

	/**
	 * Returns the miduptitle of this astra pdca_ company data.
	 *
	 * @return the miduptitle of this astra pdca_ company data
	 */
	@AutoEscape
	public String getMIDUPTITLE();

	/**
	 * Sets the miduptitle of this astra pdca_ company data.
	 *
	 * @param MIDUPTITLE the miduptitle of this astra pdca_ company data
	 */
	public void setMIDUPTITLE(String MIDUPTITLE);

	/**
	 * Returns the midupcompany of this astra pdca_ company data.
	 *
	 * @return the midupcompany of this astra pdca_ company data
	 */
	@AutoEscape
	public String getMIDUPCOMPANY();

	/**
	 * Sets the midupcompany of this astra pdca_ company data.
	 *
	 * @param MIDUPCOMPANY the midupcompany of this astra pdca_ company data
	 */
	public void setMIDUPCOMPANY(String MIDUPCOMPANY);

	/**
	 * Returns the midbottom of this astra pdca_ company data.
	 *
	 * @return the midbottom of this astra pdca_ company data
	 */
	@AutoEscape
	public String getMIDBOTTOM();

	/**
	 * Sets the midbottom of this astra pdca_ company data.
	 *
	 * @param MIDBOTTOM the midbottom of this astra pdca_ company data
	 */
	public void setMIDBOTTOM(String MIDBOTTOM);

	/**
	 * Returns the midbottomtitle of this astra pdca_ company data.
	 *
	 * @return the midbottomtitle of this astra pdca_ company data
	 */
	@AutoEscape
	public String getMIDBOTTOMTITLE();

	/**
	 * Sets the midbottomtitle of this astra pdca_ company data.
	 *
	 * @param MIDBOTTOMTITLE the midbottomtitle of this astra pdca_ company data
	 */
	public void setMIDBOTTOMTITLE(String MIDBOTTOMTITLE);

	/**
	 * Returns the midbottomcompany of this astra pdca_ company data.
	 *
	 * @return the midbottomcompany of this astra pdca_ company data
	 */
	@AutoEscape
	public String getMIDBOTTOMCOMPANY();

	/**
	 * Sets the midbottomcompany of this astra pdca_ company data.
	 *
	 * @param MIDBOTTOMCOMPANY the midbottomcompany of this astra pdca_ company data
	 */
	public void setMIDBOTTOMCOMPANY(String MIDBOTTOMCOMPANY);

	/**
	 * Returns the rightup of this astra pdca_ company data.
	 *
	 * @return the rightup of this astra pdca_ company data
	 */
	@AutoEscape
	public String getRIGHTUP();

	/**
	 * Sets the rightup of this astra pdca_ company data.
	 *
	 * @param RIGHTUP the rightup of this astra pdca_ company data
	 */
	public void setRIGHTUP(String RIGHTUP);

	/**
	 * Returns the rightuptitle of this astra pdca_ company data.
	 *
	 * @return the rightuptitle of this astra pdca_ company data
	 */
	@AutoEscape
	public String getRIGHTUPTITLE();

	/**
	 * Sets the rightuptitle of this astra pdca_ company data.
	 *
	 * @param RIGHTUPTITLE the rightuptitle of this astra pdca_ company data
	 */
	public void setRIGHTUPTITLE(String RIGHTUPTITLE);

	/**
	 * Returns the rightupcompany of this astra pdca_ company data.
	 *
	 * @return the rightupcompany of this astra pdca_ company data
	 */
	@AutoEscape
	public String getRIGHTUPCOMPANY();

	/**
	 * Sets the rightupcompany of this astra pdca_ company data.
	 *
	 * @param RIGHTUPCOMPANY the rightupcompany of this astra pdca_ company data
	 */
	public void setRIGHTUPCOMPANY(String RIGHTUPCOMPANY);

	/**
	 * Returns the rightbottom of this astra pdca_ company data.
	 *
	 * @return the rightbottom of this astra pdca_ company data
	 */
	@AutoEscape
	public String getRIGHTBOTTOM();

	/**
	 * Sets the rightbottom of this astra pdca_ company data.
	 *
	 * @param RIGHTBOTTOM the rightbottom of this astra pdca_ company data
	 */
	public void setRIGHTBOTTOM(String RIGHTBOTTOM);

	/**
	 * Returns the rightbottomtitle of this astra pdca_ company data.
	 *
	 * @return the rightbottomtitle of this astra pdca_ company data
	 */
	@AutoEscape
	public String getRIGHTBOTTOMTITLE();

	/**
	 * Sets the rightbottomtitle of this astra pdca_ company data.
	 *
	 * @param RIGHTBOTTOMTITLE the rightbottomtitle of this astra pdca_ company data
	 */
	public void setRIGHTBOTTOMTITLE(String RIGHTBOTTOMTITLE);

	/**
	 * Returns the rightbottomcompany of this astra pdca_ company data.
	 *
	 * @return the rightbottomcompany of this astra pdca_ company data
	 */
	@AutoEscape
	public String getRIGHTBOTTOMCOMPANY();

	/**
	 * Sets the rightbottomcompany of this astra pdca_ company data.
	 *
	 * @param RIGHTBOTTOMCOMPANY the rightbottomcompany of this astra pdca_ company data
	 */
	public void setRIGHTBOTTOMCOMPANY(String RIGHTBOTTOMCOMPANY);

	/**
	 * Returns the module ID of this astra pdca_ company data.
	 *
	 * @return the module ID of this astra pdca_ company data
	 */
	public long getModuleId();

	/**
	 * Sets the module ID of this astra pdca_ company data.
	 *
	 * @param ModuleId the module ID of this astra pdca_ company data
	 */
	public void setModuleId(long ModuleId);

	/**
	 * Returns the year ID of this astra pdca_ company data.
	 *
	 * @return the year ID of this astra pdca_ company data
	 */
	public long getYearId();

	/**
	 * Sets the year ID of this astra pdca_ company data.
	 *
	 * @param YearId the year ID of this astra pdca_ company data
	 */
	public void setYearId(long YearId);

	/**
	 * Returns the check flag of this astra pdca_ company data.
	 *
	 * @return the check flag of this astra pdca_ company data
	 */
	@AutoEscape
	public String getCheckFlag();

	/**
	 * Sets the check flag of this astra pdca_ company data.
	 *
	 * @param CheckFlag the check flag of this astra pdca_ company data
	 */
	public void setCheckFlag(String CheckFlag);

	/**
	 * Returns the site ID of this astra pdca_ company data.
	 *
	 * @return the site ID of this astra pdca_ company data
	 */
	public long getSiteId();

	/**
	 * Sets the site ID of this astra pdca_ company data.
	 *
	 * @param SiteId the site ID of this astra pdca_ company data
	 */
	public void setSiteId(long SiteId);

	/**
	 * Returns the create date of this astra pdca_ company data.
	 *
	 * @return the create date of this astra pdca_ company data
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this astra pdca_ company data.
	 *
	 * @param CreateDate the create date of this astra pdca_ company data
	 */
	public void setCreateDate(Date CreateDate);

	/**
	 * Returns the created by of this astra pdca_ company data.
	 *
	 * @return the created by of this astra pdca_ company data
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this astra pdca_ company data.
	 *
	 * @param CreatedBy the created by of this astra pdca_ company data
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the modified date of this astra pdca_ company data.
	 *
	 * @return the modified date of this astra pdca_ company data
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this astra pdca_ company data.
	 *
	 * @param ModifiedDate the modified date of this astra pdca_ company data
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the modified by of this astra pdca_ company data.
	 *
	 * @return the modified by of this astra pdca_ company data
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this astra pdca_ company data.
	 *
	 * @param ModifiedBy the modified by of this astra pdca_ company data
	 */
	public void setModifiedBy(String ModifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AstraPdca_CompanyData astraPdca_CompanyData);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AstraPdca_CompanyData> toCacheModel();

	@Override
	public AstraPdca_CompanyData toEscapedModel();

	@Override
	public AstraPdca_CompanyData toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}