/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.anblicks.pdca.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AstraPdca_Module service. Represents a row in the &quot;pdca_astrapdca_module&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.astra.anblicks.pdca.model.impl.AstraPdca_ModuleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.astra.anblicks.pdca.model.impl.AstraPdca_ModuleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AstraPdca_Module
 * @see com.astra.anblicks.pdca.model.impl.AstraPdca_ModuleImpl
 * @see com.astra.anblicks.pdca.model.impl.AstraPdca_ModuleModelImpl
 * @generated
 */
@ProviderType
public interface AstraPdca_ModuleModel extends BaseModel<AstraPdca_Module> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a astra pdca_ module model instance should use the {@link AstraPdca_Module} interface instead.
	 */

	/**
	 * Returns the primary key of this astra pdca_ module.
	 *
	 * @return the primary key of this astra pdca_ module
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this astra pdca_ module.
	 *
	 * @param primaryKey the primary key of this astra pdca_ module
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the module ID of this astra pdca_ module.
	 *
	 * @return the module ID of this astra pdca_ module
	 */
	public long getModuleId();

	/**
	 * Sets the module ID of this astra pdca_ module.
	 *
	 * @param ModuleId the module ID of this astra pdca_ module
	 */
	public void setModuleId(long ModuleId);

	/**
	 * Returns the module id_ company of this astra pdca_ module.
	 *
	 * @return the module id_ company of this astra pdca_ module
	 */
	public long getModuleId_Company();

	/**
	 * Sets the module id_ company of this astra pdca_ module.
	 *
	 * @param ModuleId_Company the module id_ company of this astra pdca_ module
	 */
	public void setModuleId_Company(long ModuleId_Company);

	/**
	 * Returns the module name of this astra pdca_ module.
	 *
	 * @return the module name of this astra pdca_ module
	 */
	@AutoEscape
	public String getModuleName();

	/**
	 * Sets the module name of this astra pdca_ module.
	 *
	 * @param ModuleName the module name of this astra pdca_ module
	 */
	public void setModuleName(String ModuleName);

	/**
	 * Returns the check uncheck flag of this astra pdca_ module.
	 *
	 * @return the check uncheck flag of this astra pdca_ module
	 */
	@AutoEscape
	public String getCheckUncheckFlag();

	/**
	 * Sets the check uncheck flag of this astra pdca_ module.
	 *
	 * @param checkUncheckFlag the check uncheck flag of this astra pdca_ module
	 */
	public void setCheckUncheckFlag(String checkUncheckFlag);

	/**
	 * Returns the site ID of this astra pdca_ module.
	 *
	 * @return the site ID of this astra pdca_ module
	 */
	public long getSiteId();

	/**
	 * Sets the site ID of this astra pdca_ module.
	 *
	 * @param SiteId the site ID of this astra pdca_ module
	 */
	public void setSiteId(long SiteId);

	/**
	 * Returns the create date of this astra pdca_ module.
	 *
	 * @return the create date of this astra pdca_ module
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this astra pdca_ module.
	 *
	 * @param CreateDate the create date of this astra pdca_ module
	 */
	public void setCreateDate(Date CreateDate);

	/**
	 * Returns the created by of this astra pdca_ module.
	 *
	 * @return the created by of this astra pdca_ module
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this astra pdca_ module.
	 *
	 * @param CreatedBy the created by of this astra pdca_ module
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the modified date of this astra pdca_ module.
	 *
	 * @return the modified date of this astra pdca_ module
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this astra pdca_ module.
	 *
	 * @param ModifiedDate the modified date of this astra pdca_ module
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the modified by of this astra pdca_ module.
	 *
	 * @return the modified by of this astra pdca_ module
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this astra pdca_ module.
	 *
	 * @param ModifiedBy the modified by of this astra pdca_ module
	 */
	public void setModifiedBy(String ModifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AstraPdca_Module astraPdca_Module);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AstraPdca_Module> toCacheModel();

	@Override
	public AstraPdca_Module toEscapedModel();

	@Override
	public AstraPdca_Module toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}