/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.anblicks.pdca.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the company_user service. Represents a row in the &quot;pdca_company_user&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.astra.anblicks.pdca.model.impl.company_userModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.astra.anblicks.pdca.model.impl.company_userImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see company_user
 * @see com.astra.anblicks.pdca.model.impl.company_userImpl
 * @see com.astra.anblicks.pdca.model.impl.company_userModelImpl
 * @generated
 */
@ProviderType
public interface company_userModel extends BaseModel<company_user>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a company_user model instance should use the {@link company_user} interface instead.
	 */

	/**
	 * Returns the primary key of this company_user.
	 *
	 * @return the primary key of this company_user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this company_user.
	 *
	 * @param primaryKey the primary key of this company_user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the company_user_ ID of this company_user.
	 *
	 * @return the company_user_ ID of this company_user
	 */
	public long getCompany_user_Id();

	/**
	 * Sets the company_user_ ID of this company_user.
	 *
	 * @param company_user_Id the company_user_ ID of this company_user
	 */
	public void setCompany_user_Id(long company_user_Id);

	/**
	 * Returns the company ID of this company_user.
	 *
	 * @return the company ID of this company_user
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this company_user.
	 *
	 * @param companyId the company ID of this company_user
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the pdca_user ID of this company_user.
	 *
	 * @return the pdca_user ID of this company_user
	 */
	public long getPdca_userId();

	/**
	 * Sets the pdca_user ID of this company_user.
	 *
	 * @param Pdca_userId the pdca_user ID of this company_user
	 */
	public void setPdca_userId(long Pdca_userId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.astra.anblicks.pdca.model.company_user company_user);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.astra.anblicks.pdca.model.company_user> toCacheModel();

	@Override
	public com.astra.anblicks.pdca.model.company_user toEscapedModel();

	@Override
	public com.astra.anblicks.pdca.model.company_user toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}