/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.anblicks.pdca.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ControlMOM service. Represents a row in the &quot;pdca_controlmom&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.astra.anblicks.pdca.model.impl.ControlMOMModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.astra.anblicks.pdca.model.impl.ControlMOMImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ControlMOM
 * @see com.astra.anblicks.pdca.model.impl.ControlMOMImpl
 * @see com.astra.anblicks.pdca.model.impl.ControlMOMModelImpl
 * @generated
 */
@ProviderType
public interface ControlMOMModel extends BaseModel<ControlMOM> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a control mom model instance should use the {@link ControlMOM} interface instead.
	 */

	/**
	 * Returns the primary key of this control mom.
	 *
	 * @return the primary key of this control mom
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this control mom.
	 *
	 * @param primaryKey the primary key of this control mom
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the control mom ID of this control mom.
	 *
	 * @return the control mom ID of this control mom
	 */
	public long getControlMOMId();

	/**
	 * Sets the control mom ID of this control mom.
	 *
	 * @param ControlMOMId the control mom ID of this control mom
	 */
	public void setControlMOMId(long ControlMOMId);

	/**
	 * Returns the list mom ID of this control mom.
	 *
	 * @return the list mom ID of this control mom
	 */
	public long getListMOMId();

	/**
	 * Sets the list mom ID of this control mom.
	 *
	 * @param ListMOMId the list mom ID of this control mom
	 */
	public void setListMOMId(long ListMOMId);

	/**
	 * Returns the pd ID of this control mom.
	 *
	 * @return the pd ID of this control mom
	 */
	public long getPdId();

	/**
	 * Sets the pd ID of this control mom.
	 *
	 * @param pdId the pd ID of this control mom
	 */
	public void setPdId(long pdId);

	/**
	 * Returns the user ID of this control mom.
	 *
	 * @return the user ID of this control mom
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this control mom.
	 *
	 * @param userId the user ID of this control mom
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this control mom.
	 *
	 * @return the user uuid of this control mom
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this control mom.
	 *
	 * @param userUuid the user uuid of this control mom
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the status of this control mom.
	 *
	 * @return the status of this control mom
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this control mom.
	 *
	 * @param Status the status of this control mom
	 */
	public void setStatus(String Status);

	/**
	 * Returns the follow up of this control mom.
	 *
	 * @return the follow up of this control mom
	 */
	@AutoEscape
	public String getFollowUp();

	/**
	 * Sets the follow up of this control mom.
	 *
	 * @param FollowUp the follow up of this control mom
	 */
	public void setFollowUp(String FollowUp);

	/**
	 * Returns the follow up data of this control mom.
	 *
	 * @return the follow up data of this control mom
	 */
	@AutoEscape
	public String getFollowUpData();

	/**
	 * Sets the follow up data of this control mom.
	 *
	 * @param FollowUpData the follow up data of this control mom
	 */
	public void setFollowUpData(String FollowUpData);

	/**
	 * Returns the site ID of this control mom.
	 *
	 * @return the site ID of this control mom
	 */
	public long getSiteId();

	/**
	 * Sets the site ID of this control mom.
	 *
	 * @param SiteId the site ID of this control mom
	 */
	public void setSiteId(long SiteId);

	/**
	 * Returns the create date of this control mom.
	 *
	 * @return the create date of this control mom
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this control mom.
	 *
	 * @param CreateDate the create date of this control mom
	 */
	public void setCreateDate(Date CreateDate);

	/**
	 * Returns the created by of this control mom.
	 *
	 * @return the created by of this control mom
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this control mom.
	 *
	 * @param CreatedBy the created by of this control mom
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the modified date of this control mom.
	 *
	 * @return the modified date of this control mom
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this control mom.
	 *
	 * @param ModifiedDate the modified date of this control mom
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the modified by of this control mom.
	 *
	 * @return the modified by of this control mom
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this control mom.
	 *
	 * @param ModifiedBy the modified by of this control mom
	 */
	public void setModifiedBy(String ModifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ControlMOM controlMOM);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ControlMOM> toCacheModel();

	@Override
	public ControlMOM toEscapedModel();

	@Override
	public ControlMOM toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}