/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.anblicks.pdca.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ListMOM service. Represents a row in the &quot;pdca_listmom&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.astra.anblicks.pdca.model.impl.ListMOMModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.astra.anblicks.pdca.model.impl.ListMOMImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ListMOM
 * @see com.astra.anblicks.pdca.model.impl.ListMOMImpl
 * @see com.astra.anblicks.pdca.model.impl.ListMOMModelImpl
 * @generated
 */
@ProviderType
public interface ListMOMModel extends BaseModel<ListMOM>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a list mom model instance should use the {@link ListMOM} interface instead.
	 */

	/**
	 * Returns the primary key of this list mom.
	 *
	 * @return the primary key of this list mom
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this list mom.
	 *
	 * @param primaryKey the primary key of this list mom
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mom ID of this list mom.
	 *
	 * @return the mom ID of this list mom
	 */
	public long getMomId();

	/**
	 * Sets the mom ID of this list mom.
	 *
	 * @param MomId the mom ID of this list mom
	 */
	public void setMomId(long MomId);

	/**
	 * Returns the user ID of this list mom.
	 *
	 * @return the user ID of this list mom
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this list mom.
	 *
	 * @param userId the user ID of this list mom
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this list mom.
	 *
	 * @return the user uuid of this list mom
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this list mom.
	 *
	 * @param userUuid the user uuid of this list mom
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the company ID of this list mom.
	 *
	 * @return the company ID of this list mom
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this list mom.
	 *
	 * @param companyId the company ID of this list mom
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the meeting date of this list mom.
	 *
	 * @return the meeting date of this list mom
	 */
	@AutoEscape
	public String getMeetingDate();

	/**
	 * Sets the meeting date of this list mom.
	 *
	 * @param meetingDate the meeting date of this list mom
	 */
	public void setMeetingDate(String meetingDate);

	/**
	 * Returns the from time of this list mom.
	 *
	 * @return the from time of this list mom
	 */
	@AutoEscape
	public String getFromTime();

	/**
	 * Sets the from time of this list mom.
	 *
	 * @param fromTime the from time of this list mom
	 */
	public void setFromTime(String fromTime);

	/**
	 * Returns the ampm of this list mom.
	 *
	 * @return the ampm of this list mom
	 */
	@AutoEscape
	public String getAmpm();

	/**
	 * Sets the ampm of this list mom.
	 *
	 * @param ampm the ampm of this list mom
	 */
	public void setAmpm(String ampm);

	/**
	 * Returns the mom type of this list mom.
	 *
	 * @return the mom type of this list mom
	 */
	@AutoEscape
	public String getMomType();

	/**
	 * Sets the mom type of this list mom.
	 *
	 * @param MomType the mom type of this list mom
	 */
	public void setMomType(String MomType);

	/**
	 * Returns the mom type ID of this list mom.
	 *
	 * @return the mom type ID of this list mom
	 */
	@AutoEscape
	public String getMomTypeId();

	/**
	 * Sets the mom type ID of this list mom.
	 *
	 * @param MomTypeId the mom type ID of this list mom
	 */
	public void setMomTypeId(String MomTypeId);

	/**
	 * Returns the performance of this list mom.
	 *
	 * @return the performance of this list mom
	 */
	@AutoEscape
	public String getPerformance();

	/**
	 * Sets the performance of this list mom.
	 *
	 * @param performance the performance of this list mom
	 */
	public void setPerformance(String performance);

	/**
	 * Returns the mom group of this list mom.
	 *
	 * @return the mom group of this list mom
	 */
	@AutoEscape
	public String getMOMGroup();

	/**
	 * Sets the mom group of this list mom.
	 *
	 * @param MOMGroup the mom group of this list mom
	 */
	public void setMOMGroup(String MOMGroup);

	/**
	 * Returns the mo mparticipants of this list mom.
	 *
	 * @return the mo mparticipants of this list mom
	 */
	@AutoEscape
	public String getMOMparticipants();

	/**
	 * Sets the mo mparticipants of this list mom.
	 *
	 * @param MOMparticipants the mo mparticipants of this list mom
	 */
	public void setMOMparticipants(String MOMparticipants);

	/**
	 * Returns the mo mcompany name of this list mom.
	 *
	 * @return the mo mcompany name of this list mom
	 */
	@AutoEscape
	public String getMOMcompanyName();

	/**
	 * Sets the mo mcompany name of this list mom.
	 *
	 * @param MOMcompanyName the mo mcompany name of this list mom
	 */
	public void setMOMcompanyName(String MOMcompanyName);

	/**
	 * Returns the mo mplace of this list mom.
	 *
	 * @return the mo mplace of this list mom
	 */
	@AutoEscape
	public String getMOMplace();

	/**
	 * Sets the mo mplace of this list mom.
	 *
	 * @param MOMplace the mo mplace of this list mom
	 */
	public void setMOMplace(String MOMplace);

	/**
	 * Returns the ponit discussion ID of this list mom.
	 *
	 * @return the ponit discussion ID of this list mom
	 */
	public long getPonitDiscussionId();

	/**
	 * Sets the ponit discussion ID of this list mom.
	 *
	 * @param ponitDiscussionId the ponit discussion ID of this list mom
	 */
	public void setPonitDiscussionId(long ponitDiscussionId);

	/**
	 * Returns the site ID of this list mom.
	 *
	 * @return the site ID of this list mom
	 */
	public long getSiteId();

	/**
	 * Sets the site ID of this list mom.
	 *
	 * @param SiteId the site ID of this list mom
	 */
	public void setSiteId(long SiteId);

	/**
	 * Returns the create date of this list mom.
	 *
	 * @return the create date of this list mom
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this list mom.
	 *
	 * @param CreateDate the create date of this list mom
	 */
	public void setCreateDate(Date CreateDate);

	/**
	 * Returns the created by of this list mom.
	 *
	 * @return the created by of this list mom
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this list mom.
	 *
	 * @param CreatedBy the created by of this list mom
	 */
	public void setCreatedBy(String CreatedBy);

	/**
	 * Returns the modified date of this list mom.
	 *
	 * @return the modified date of this list mom
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this list mom.
	 *
	 * @param ModifiedDate the modified date of this list mom
	 */
	public void setModifiedDate(Date ModifiedDate);

	/**
	 * Returns the modified by of this list mom.
	 *
	 * @return the modified by of this list mom
	 */
	@AutoEscape
	public String getModifiedBy();

	/**
	 * Sets the modified by of this list mom.
	 *
	 * @param ModifiedBy the modified by of this list mom
	 */
	public void setModifiedBy(String ModifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ListMOM listMOM);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ListMOM> toCacheModel();

	@Override
	public ListMOM toEscapedModel();

	@Override
	public ListMOM toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}