/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.anblicks.pdca.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the period service. Represents a row in the &quot;pdca_period&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.astra.anblicks.pdca.model.impl.periodModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.astra.anblicks.pdca.model.impl.periodImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see period
 * @see com.astra.anblicks.pdca.model.impl.periodImpl
 * @see com.astra.anblicks.pdca.model.impl.periodModelImpl
 * @generated
 */
@ProviderType
public interface periodModel extends BaseModel<period> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a period model instance should use the {@link period} interface instead.
	 */

	/**
	 * Returns the primary key of this period.
	 *
	 * @return the primary key of this period
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this period.
	 *
	 * @param primaryKey the primary key of this period
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this period.
	 *
	 * @return the uuid of this period
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this period.
	 *
	 * @param uuid the uuid of this period
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the period ID of this period.
	 *
	 * @return the period ID of this period
	 */
	public long getPeriodId();

	/**
	 * Sets the period ID of this period.
	 *
	 * @param periodId the period ID of this period
	 */
	public void setPeriodId(long periodId);

	/**
	 * Returns the period name of this period.
	 *
	 * @return the period name of this period
	 */
	@AutoEscape
	public String getPeriodName();

	/**
	 * Sets the period name of this period.
	 *
	 * @param periodName the period name of this period
	 */
	public void setPeriodName(String periodName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.astra.anblicks.pdca.model.period period);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.astra.anblicks.pdca.model.period> toCacheModel();

	@Override
	public com.astra.anblicks.pdca.model.period toEscapedModel();

	@Override
	public com.astra.anblicks.pdca.model.period toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}