/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.anblicks.pdca.service.base;

import aQute.bnd.annotation.ProviderType;

import com.astra.anblicks.pdca.model.AstraPdca_Module;
import com.astra.anblicks.pdca.service.AstraPdca_ModuleLocalService;
import com.astra.anblicks.pdca.service.persistence.AstraPdca_CompanyDataPersistence;
import com.astra.anblicks.pdca.service.persistence.AstraPdca_ModulePersistence;
import com.astra.anblicks.pdca.service.persistence.AstraPdca_YearPersistence;
import com.astra.anblicks.pdca.service.persistence.ControlMOMPersistence;
import com.astra.anblicks.pdca.service.persistence.ListMOMPersistence;
import com.astra.anblicks.pdca.service.persistence.MOMPointdiscussoinPersistence;
import com.astra.anblicks.pdca.service.persistence.achivementFormulaPersistence;
import com.astra.anblicks.pdca.service.persistence.cla_kpiPersistence;
import com.astra.anblicks.pdca.service.persistence.company_userPersistence;
import com.astra.anblicks.pdca.service.persistence.itemDescriptionPersistence;
import com.astra.anblicks.pdca.service.persistence.kpiPersistence;
import com.astra.anblicks.pdca.service.persistence.pdca_AdminSettingsPersistence;
import com.astra.anblicks.pdca.service.persistence.periodPersistence;
import com.astra.anblicks.pdca.service.persistence.tradingProfitPersistence;
import com.astra.anblicks.pdca.service.persistence.typePersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the astra pdca_ module local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.astra.anblicks.pdca.service.impl.AstraPdca_ModuleLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.astra.anblicks.pdca.service.impl.AstraPdca_ModuleLocalServiceImpl
 * @see com.astra.anblicks.pdca.service.AstraPdca_ModuleLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class AstraPdca_ModuleLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements AstraPdca_ModuleLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.astra.anblicks.pdca.service.AstraPdca_ModuleLocalServiceUtil} to access the astra pdca_ module local service.
	 */

	/**
	 * Adds the astra pdca_ module to the database. Also notifies the appropriate model listeners.
	 *
	 * @param astraPdca_Module the astra pdca_ module
	 * @return the astra pdca_ module that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AstraPdca_Module addAstraPdca_Module(
		AstraPdca_Module astraPdca_Module) {
		astraPdca_Module.setNew(true);

		return astraPdca_ModulePersistence.update(astraPdca_Module);
	}

	/**
	 * Creates a new astra pdca_ module with the primary key. Does not add the astra pdca_ module to the database.
	 *
	 * @param ModuleId the primary key for the new astra pdca_ module
	 * @return the new astra pdca_ module
	 */
	@Override
	public AstraPdca_Module createAstraPdca_Module(long ModuleId) {
		return astraPdca_ModulePersistence.create(ModuleId);
	}

	/**
	 * Deletes the astra pdca_ module with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param ModuleId the primary key of the astra pdca_ module
	 * @return the astra pdca_ module that was removed
	 * @throws PortalException if a astra pdca_ module with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AstraPdca_Module deleteAstraPdca_Module(long ModuleId)
		throws PortalException {
		return astraPdca_ModulePersistence.remove(ModuleId);
	}

	/**
	 * Deletes the astra pdca_ module from the database. Also notifies the appropriate model listeners.
	 *
	 * @param astraPdca_Module the astra pdca_ module
	 * @return the astra pdca_ module that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AstraPdca_Module deleteAstraPdca_Module(
		AstraPdca_Module astraPdca_Module) {
		return astraPdca_ModulePersistence.remove(astraPdca_Module);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(AstraPdca_Module.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return astraPdca_ModulePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.astra.anblicks.pdca.model.impl.AstraPdca_ModuleModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return astraPdca_ModulePersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.astra.anblicks.pdca.model.impl.AstraPdca_ModuleModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return astraPdca_ModulePersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return astraPdca_ModulePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return astraPdca_ModulePersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public AstraPdca_Module fetchAstraPdca_Module(long ModuleId) {
		return astraPdca_ModulePersistence.fetchByPrimaryKey(ModuleId);
	}

	/**
	 * Returns the astra pdca_ module with the primary key.
	 *
	 * @param ModuleId the primary key of the astra pdca_ module
	 * @return the astra pdca_ module
	 * @throws PortalException if a astra pdca_ module with the primary key could not be found
	 */
	@Override
	public AstraPdca_Module getAstraPdca_Module(long ModuleId)
		throws PortalException {
		return astraPdca_ModulePersistence.findByPrimaryKey(ModuleId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(astraPdca_ModuleLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AstraPdca_Module.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("ModuleId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(astraPdca_ModuleLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(AstraPdca_Module.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("ModuleId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(astraPdca_ModuleLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AstraPdca_Module.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("ModuleId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return astraPdca_ModuleLocalService.deleteAstraPdca_Module((AstraPdca_Module)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return astraPdca_ModulePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the astra pdca_ modules.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.astra.anblicks.pdca.model.impl.AstraPdca_ModuleModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of astra pdca_ modules
	 * @param end the upper bound of the range of astra pdca_ modules (not inclusive)
	 * @return the range of astra pdca_ modules
	 */
	@Override
	public List<AstraPdca_Module> getAstraPdca_Modules(int start, int end) {
		return astraPdca_ModulePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of astra pdca_ modules.
	 *
	 * @return the number of astra pdca_ modules
	 */
	@Override
	public int getAstraPdca_ModulesCount() {
		return astraPdca_ModulePersistence.countAll();
	}

	/**
	 * Updates the astra pdca_ module in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param astraPdca_Module the astra pdca_ module
	 * @return the astra pdca_ module that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AstraPdca_Module updateAstraPdca_Module(
		AstraPdca_Module astraPdca_Module) {
		return astraPdca_ModulePersistence.update(astraPdca_Module);
	}

	/**
	 * Returns the achivement formula local service.
	 *
	 * @return the achivement formula local service
	 */
	public com.astra.anblicks.pdca.service.achivementFormulaLocalService getachivementFormulaLocalService() {
		return achivementFormulaLocalService;
	}

	/**
	 * Sets the achivement formula local service.
	 *
	 * @param achivementFormulaLocalService the achivement formula local service
	 */
	public void setachivementFormulaLocalService(
		com.astra.anblicks.pdca.service.achivementFormulaLocalService achivementFormulaLocalService) {
		this.achivementFormulaLocalService = achivementFormulaLocalService;
	}

	/**
	 * Returns the achivement formula persistence.
	 *
	 * @return the achivement formula persistence
	 */
	public achivementFormulaPersistence getachivementFormulaPersistence() {
		return achivementFormulaPersistence;
	}

	/**
	 * Sets the achivement formula persistence.
	 *
	 * @param achivementFormulaPersistence the achivement formula persistence
	 */
	public void setachivementFormulaPersistence(
		achivementFormulaPersistence achivementFormulaPersistence) {
		this.achivementFormulaPersistence = achivementFormulaPersistence;
	}

	/**
	 * Returns the astra pdca_ company data local service.
	 *
	 * @return the astra pdca_ company data local service
	 */
	public com.astra.anblicks.pdca.service.AstraPdca_CompanyDataLocalService getAstraPdca_CompanyDataLocalService() {
		return astraPdca_CompanyDataLocalService;
	}

	/**
	 * Sets the astra pdca_ company data local service.
	 *
	 * @param astraPdca_CompanyDataLocalService the astra pdca_ company data local service
	 */
	public void setAstraPdca_CompanyDataLocalService(
		com.astra.anblicks.pdca.service.AstraPdca_CompanyDataLocalService astraPdca_CompanyDataLocalService) {
		this.astraPdca_CompanyDataLocalService = astraPdca_CompanyDataLocalService;
	}

	/**
	 * Returns the astra pdca_ company data persistence.
	 *
	 * @return the astra pdca_ company data persistence
	 */
	public AstraPdca_CompanyDataPersistence getAstraPdca_CompanyDataPersistence() {
		return astraPdca_CompanyDataPersistence;
	}

	/**
	 * Sets the astra pdca_ company data persistence.
	 *
	 * @param astraPdca_CompanyDataPersistence the astra pdca_ company data persistence
	 */
	public void setAstraPdca_CompanyDataPersistence(
		AstraPdca_CompanyDataPersistence astraPdca_CompanyDataPersistence) {
		this.astraPdca_CompanyDataPersistence = astraPdca_CompanyDataPersistence;
	}

	/**
	 * Returns the astra pdca_ module local service.
	 *
	 * @return the astra pdca_ module local service
	 */
	public AstraPdca_ModuleLocalService getAstraPdca_ModuleLocalService() {
		return astraPdca_ModuleLocalService;
	}

	/**
	 * Sets the astra pdca_ module local service.
	 *
	 * @param astraPdca_ModuleLocalService the astra pdca_ module local service
	 */
	public void setAstraPdca_ModuleLocalService(
		AstraPdca_ModuleLocalService astraPdca_ModuleLocalService) {
		this.astraPdca_ModuleLocalService = astraPdca_ModuleLocalService;
	}

	/**
	 * Returns the astra pdca_ module persistence.
	 *
	 * @return the astra pdca_ module persistence
	 */
	public AstraPdca_ModulePersistence getAstraPdca_ModulePersistence() {
		return astraPdca_ModulePersistence;
	}

	/**
	 * Sets the astra pdca_ module persistence.
	 *
	 * @param astraPdca_ModulePersistence the astra pdca_ module persistence
	 */
	public void setAstraPdca_ModulePersistence(
		AstraPdca_ModulePersistence astraPdca_ModulePersistence) {
		this.astraPdca_ModulePersistence = astraPdca_ModulePersistence;
	}

	/**
	 * Returns the astra pdca_ year local service.
	 *
	 * @return the astra pdca_ year local service
	 */
	public com.astra.anblicks.pdca.service.AstraPdca_YearLocalService getAstraPdca_YearLocalService() {
		return astraPdca_YearLocalService;
	}

	/**
	 * Sets the astra pdca_ year local service.
	 *
	 * @param astraPdca_YearLocalService the astra pdca_ year local service
	 */
	public void setAstraPdca_YearLocalService(
		com.astra.anblicks.pdca.service.AstraPdca_YearLocalService astraPdca_YearLocalService) {
		this.astraPdca_YearLocalService = astraPdca_YearLocalService;
	}

	/**
	 * Returns the astra pdca_ year persistence.
	 *
	 * @return the astra pdca_ year persistence
	 */
	public AstraPdca_YearPersistence getAstraPdca_YearPersistence() {
		return astraPdca_YearPersistence;
	}

	/**
	 * Sets the astra pdca_ year persistence.
	 *
	 * @param astraPdca_YearPersistence the astra pdca_ year persistence
	 */
	public void setAstraPdca_YearPersistence(
		AstraPdca_YearPersistence astraPdca_YearPersistence) {
		this.astraPdca_YearPersistence = astraPdca_YearPersistence;
	}

	/**
	 * Returns the cla_kpi local service.
	 *
	 * @return the cla_kpi local service
	 */
	public com.astra.anblicks.pdca.service.cla_kpiLocalService getcla_kpiLocalService() {
		return cla_kpiLocalService;
	}

	/**
	 * Sets the cla_kpi local service.
	 *
	 * @param cla_kpiLocalService the cla_kpi local service
	 */
	public void setcla_kpiLocalService(
		com.astra.anblicks.pdca.service.cla_kpiLocalService cla_kpiLocalService) {
		this.cla_kpiLocalService = cla_kpiLocalService;
	}

	/**
	 * Returns the cla_kpi persistence.
	 *
	 * @return the cla_kpi persistence
	 */
	public cla_kpiPersistence getcla_kpiPersistence() {
		return cla_kpiPersistence;
	}

	/**
	 * Sets the cla_kpi persistence.
	 *
	 * @param cla_kpiPersistence the cla_kpi persistence
	 */
	public void setcla_kpiPersistence(cla_kpiPersistence cla_kpiPersistence) {
		this.cla_kpiPersistence = cla_kpiPersistence;
	}

	/**
	 * Returns the company_user local service.
	 *
	 * @return the company_user local service
	 */
	public com.astra.anblicks.pdca.service.company_userLocalService getcompany_userLocalService() {
		return company_userLocalService;
	}

	/**
	 * Sets the company_user local service.
	 *
	 * @param company_userLocalService the company_user local service
	 */
	public void setcompany_userLocalService(
		com.astra.anblicks.pdca.service.company_userLocalService company_userLocalService) {
		this.company_userLocalService = company_userLocalService;
	}

	/**
	 * Returns the company_user persistence.
	 *
	 * @return the company_user persistence
	 */
	public company_userPersistence getcompany_userPersistence() {
		return company_userPersistence;
	}

	/**
	 * Sets the company_user persistence.
	 *
	 * @param company_userPersistence the company_user persistence
	 */
	public void setcompany_userPersistence(
		company_userPersistence company_userPersistence) {
		this.company_userPersistence = company_userPersistence;
	}

	/**
	 * Returns the control mom local service.
	 *
	 * @return the control mom local service
	 */
	public com.astra.anblicks.pdca.service.ControlMOMLocalService getControlMOMLocalService() {
		return controlMOMLocalService;
	}

	/**
	 * Sets the control mom local service.
	 *
	 * @param controlMOMLocalService the control mom local service
	 */
	public void setControlMOMLocalService(
		com.astra.anblicks.pdca.service.ControlMOMLocalService controlMOMLocalService) {
		this.controlMOMLocalService = controlMOMLocalService;
	}

	/**
	 * Returns the control mom persistence.
	 *
	 * @return the control mom persistence
	 */
	public ControlMOMPersistence getControlMOMPersistence() {
		return controlMOMPersistence;
	}

	/**
	 * Sets the control mom persistence.
	 *
	 * @param controlMOMPersistence the control mom persistence
	 */
	public void setControlMOMPersistence(
		ControlMOMPersistence controlMOMPersistence) {
		this.controlMOMPersistence = controlMOMPersistence;
	}

	/**
	 * Returns the item description local service.
	 *
	 * @return the item description local service
	 */
	public com.astra.anblicks.pdca.service.itemDescriptionLocalService getitemDescriptionLocalService() {
		return itemDescriptionLocalService;
	}

	/**
	 * Sets the item description local service.
	 *
	 * @param itemDescriptionLocalService the item description local service
	 */
	public void setitemDescriptionLocalService(
		com.astra.anblicks.pdca.service.itemDescriptionLocalService itemDescriptionLocalService) {
		this.itemDescriptionLocalService = itemDescriptionLocalService;
	}

	/**
	 * Returns the item description persistence.
	 *
	 * @return the item description persistence
	 */
	public itemDescriptionPersistence getitemDescriptionPersistence() {
		return itemDescriptionPersistence;
	}

	/**
	 * Sets the item description persistence.
	 *
	 * @param itemDescriptionPersistence the item description persistence
	 */
	public void setitemDescriptionPersistence(
		itemDescriptionPersistence itemDescriptionPersistence) {
		this.itemDescriptionPersistence = itemDescriptionPersistence;
	}

	/**
	 * Returns the kpi local service.
	 *
	 * @return the kpi local service
	 */
	public com.astra.anblicks.pdca.service.kpiLocalService getkpiLocalService() {
		return kpiLocalService;
	}

	/**
	 * Sets the kpi local service.
	 *
	 * @param kpiLocalService the kpi local service
	 */
	public void setkpiLocalService(
		com.astra.anblicks.pdca.service.kpiLocalService kpiLocalService) {
		this.kpiLocalService = kpiLocalService;
	}

	/**
	 * Returns the kpi persistence.
	 *
	 * @return the kpi persistence
	 */
	public kpiPersistence getkpiPersistence() {
		return kpiPersistence;
	}

	/**
	 * Sets the kpi persistence.
	 *
	 * @param kpiPersistence the kpi persistence
	 */
	public void setkpiPersistence(kpiPersistence kpiPersistence) {
		this.kpiPersistence = kpiPersistence;
	}

	/**
	 * Returns the list mom local service.
	 *
	 * @return the list mom local service
	 */
	public com.astra.anblicks.pdca.service.ListMOMLocalService getListMOMLocalService() {
		return listMOMLocalService;
	}

	/**
	 * Sets the list mom local service.
	 *
	 * @param listMOMLocalService the list mom local service
	 */
	public void setListMOMLocalService(
		com.astra.anblicks.pdca.service.ListMOMLocalService listMOMLocalService) {
		this.listMOMLocalService = listMOMLocalService;
	}

	/**
	 * Returns the list mom persistence.
	 *
	 * @return the list mom persistence
	 */
	public ListMOMPersistence getListMOMPersistence() {
		return listMOMPersistence;
	}

	/**
	 * Sets the list mom persistence.
	 *
	 * @param listMOMPersistence the list mom persistence
	 */
	public void setListMOMPersistence(ListMOMPersistence listMOMPersistence) {
		this.listMOMPersistence = listMOMPersistence;
	}

	/**
	 * Returns the mom pointdiscussoin local service.
	 *
	 * @return the mom pointdiscussoin local service
	 */
	public com.astra.anblicks.pdca.service.MOMPointdiscussoinLocalService getMOMPointdiscussoinLocalService() {
		return momPointdiscussoinLocalService;
	}

	/**
	 * Sets the mom pointdiscussoin local service.
	 *
	 * @param momPointdiscussoinLocalService the mom pointdiscussoin local service
	 */
	public void setMOMPointdiscussoinLocalService(
		com.astra.anblicks.pdca.service.MOMPointdiscussoinLocalService momPointdiscussoinLocalService) {
		this.momPointdiscussoinLocalService = momPointdiscussoinLocalService;
	}

	/**
	 * Returns the mom pointdiscussoin persistence.
	 *
	 * @return the mom pointdiscussoin persistence
	 */
	public MOMPointdiscussoinPersistence getMOMPointdiscussoinPersistence() {
		return momPointdiscussoinPersistence;
	}

	/**
	 * Sets the mom pointdiscussoin persistence.
	 *
	 * @param momPointdiscussoinPersistence the mom pointdiscussoin persistence
	 */
	public void setMOMPointdiscussoinPersistence(
		MOMPointdiscussoinPersistence momPointdiscussoinPersistence) {
		this.momPointdiscussoinPersistence = momPointdiscussoinPersistence;
	}

	/**
	 * Returns the pdca_ admin settings local service.
	 *
	 * @return the pdca_ admin settings local service
	 */
	public com.astra.anblicks.pdca.service.pdca_AdminSettingsLocalService getpdca_AdminSettingsLocalService() {
		return pdca_AdminSettingsLocalService;
	}

	/**
	 * Sets the pdca_ admin settings local service.
	 *
	 * @param pdca_AdminSettingsLocalService the pdca_ admin settings local service
	 */
	public void setpdca_AdminSettingsLocalService(
		com.astra.anblicks.pdca.service.pdca_AdminSettingsLocalService pdca_AdminSettingsLocalService) {
		this.pdca_AdminSettingsLocalService = pdca_AdminSettingsLocalService;
	}

	/**
	 * Returns the pdca_ admin settings persistence.
	 *
	 * @return the pdca_ admin settings persistence
	 */
	public pdca_AdminSettingsPersistence getpdca_AdminSettingsPersistence() {
		return pdca_AdminSettingsPersistence;
	}

	/**
	 * Sets the pdca_ admin settings persistence.
	 *
	 * @param pdca_AdminSettingsPersistence the pdca_ admin settings persistence
	 */
	public void setpdca_AdminSettingsPersistence(
		pdca_AdminSettingsPersistence pdca_AdminSettingsPersistence) {
		this.pdca_AdminSettingsPersistence = pdca_AdminSettingsPersistence;
	}

	/**
	 * Returns the period local service.
	 *
	 * @return the period local service
	 */
	public com.astra.anblicks.pdca.service.periodLocalService getperiodLocalService() {
		return periodLocalService;
	}

	/**
	 * Sets the period local service.
	 *
	 * @param periodLocalService the period local service
	 */
	public void setperiodLocalService(
		com.astra.anblicks.pdca.service.periodLocalService periodLocalService) {
		this.periodLocalService = periodLocalService;
	}

	/**
	 * Returns the period persistence.
	 *
	 * @return the period persistence
	 */
	public periodPersistence getperiodPersistence() {
		return periodPersistence;
	}

	/**
	 * Sets the period persistence.
	 *
	 * @param periodPersistence the period persistence
	 */
	public void setperiodPersistence(periodPersistence periodPersistence) {
		this.periodPersistence = periodPersistence;
	}

	/**
	 * Returns the trading profit local service.
	 *
	 * @return the trading profit local service
	 */
	public com.astra.anblicks.pdca.service.tradingProfitLocalService gettradingProfitLocalService() {
		return tradingProfitLocalService;
	}

	/**
	 * Sets the trading profit local service.
	 *
	 * @param tradingProfitLocalService the trading profit local service
	 */
	public void settradingProfitLocalService(
		com.astra.anblicks.pdca.service.tradingProfitLocalService tradingProfitLocalService) {
		this.tradingProfitLocalService = tradingProfitLocalService;
	}

	/**
	 * Returns the trading profit persistence.
	 *
	 * @return the trading profit persistence
	 */
	public tradingProfitPersistence gettradingProfitPersistence() {
		return tradingProfitPersistence;
	}

	/**
	 * Sets the trading profit persistence.
	 *
	 * @param tradingProfitPersistence the trading profit persistence
	 */
	public void settradingProfitPersistence(
		tradingProfitPersistence tradingProfitPersistence) {
		this.tradingProfitPersistence = tradingProfitPersistence;
	}

	/**
	 * Returns the type local service.
	 *
	 * @return the type local service
	 */
	public com.astra.anblicks.pdca.service.typeLocalService gettypeLocalService() {
		return typeLocalService;
	}

	/**
	 * Sets the type local service.
	 *
	 * @param typeLocalService the type local service
	 */
	public void settypeLocalService(
		com.astra.anblicks.pdca.service.typeLocalService typeLocalService) {
		this.typeLocalService = typeLocalService;
	}

	/**
	 * Returns the type persistence.
	 *
	 * @return the type persistence
	 */
	public typePersistence gettypePersistence() {
		return typePersistence;
	}

	/**
	 * Sets the type persistence.
	 *
	 * @param typePersistence the type persistence
	 */
	public void settypePersistence(typePersistence typePersistence) {
		this.typePersistence = typePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.astra.anblicks.pdca.model.AstraPdca_Module",
			astraPdca_ModuleLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.astra.anblicks.pdca.model.AstraPdca_Module");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AstraPdca_ModuleLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AstraPdca_Module.class;
	}

	protected String getModelClassName() {
		return AstraPdca_Module.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = astraPdca_ModulePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.astra.anblicks.pdca.service.achivementFormulaLocalService.class)
	protected com.astra.anblicks.pdca.service.achivementFormulaLocalService achivementFormulaLocalService;
	@BeanReference(type = achivementFormulaPersistence.class)
	protected achivementFormulaPersistence achivementFormulaPersistence;
	@BeanReference(type = com.astra.anblicks.pdca.service.AstraPdca_CompanyDataLocalService.class)
	protected com.astra.anblicks.pdca.service.AstraPdca_CompanyDataLocalService astraPdca_CompanyDataLocalService;
	@BeanReference(type = AstraPdca_CompanyDataPersistence.class)
	protected AstraPdca_CompanyDataPersistence astraPdca_CompanyDataPersistence;
	@BeanReference(type = AstraPdca_ModuleLocalService.class)
	protected AstraPdca_ModuleLocalService astraPdca_ModuleLocalService;
	@BeanReference(type = AstraPdca_ModulePersistence.class)
	protected AstraPdca_ModulePersistence astraPdca_ModulePersistence;
	@BeanReference(type = com.astra.anblicks.pdca.service.AstraPdca_YearLocalService.class)
	protected com.astra.anblicks.pdca.service.AstraPdca_YearLocalService astraPdca_YearLocalService;
	@BeanReference(type = AstraPdca_YearPersistence.class)
	protected AstraPdca_YearPersistence astraPdca_YearPersistence;
	@BeanReference(type = com.astra.anblicks.pdca.service.cla_kpiLocalService.class)
	protected com.astra.anblicks.pdca.service.cla_kpiLocalService cla_kpiLocalService;
	@BeanReference(type = cla_kpiPersistence.class)
	protected cla_kpiPersistence cla_kpiPersistence;
	@BeanReference(type = com.astra.anblicks.pdca.service.company_userLocalService.class)
	protected com.astra.anblicks.pdca.service.company_userLocalService company_userLocalService;
	@BeanReference(type = company_userPersistence.class)
	protected company_userPersistence company_userPersistence;
	@BeanReference(type = com.astra.anblicks.pdca.service.ControlMOMLocalService.class)
	protected com.astra.anblicks.pdca.service.ControlMOMLocalService controlMOMLocalService;
	@BeanReference(type = ControlMOMPersistence.class)
	protected ControlMOMPersistence controlMOMPersistence;
	@BeanReference(type = com.astra.anblicks.pdca.service.itemDescriptionLocalService.class)
	protected com.astra.anblicks.pdca.service.itemDescriptionLocalService itemDescriptionLocalService;
	@BeanReference(type = itemDescriptionPersistence.class)
	protected itemDescriptionPersistence itemDescriptionPersistence;
	@BeanReference(type = com.astra.anblicks.pdca.service.kpiLocalService.class)
	protected com.astra.anblicks.pdca.service.kpiLocalService kpiLocalService;
	@BeanReference(type = kpiPersistence.class)
	protected kpiPersistence kpiPersistence;
	@BeanReference(type = com.astra.anblicks.pdca.service.ListMOMLocalService.class)
	protected com.astra.anblicks.pdca.service.ListMOMLocalService listMOMLocalService;
	@BeanReference(type = ListMOMPersistence.class)
	protected ListMOMPersistence listMOMPersistence;
	@BeanReference(type = com.astra.anblicks.pdca.service.MOMPointdiscussoinLocalService.class)
	protected com.astra.anblicks.pdca.service.MOMPointdiscussoinLocalService momPointdiscussoinLocalService;
	@BeanReference(type = MOMPointdiscussoinPersistence.class)
	protected MOMPointdiscussoinPersistence momPointdiscussoinPersistence;
	@BeanReference(type = com.astra.anblicks.pdca.service.pdca_AdminSettingsLocalService.class)
	protected com.astra.anblicks.pdca.service.pdca_AdminSettingsLocalService pdca_AdminSettingsLocalService;
	@BeanReference(type = pdca_AdminSettingsPersistence.class)
	protected pdca_AdminSettingsPersistence pdca_AdminSettingsPersistence;
	@BeanReference(type = com.astra.anblicks.pdca.service.periodLocalService.class)
	protected com.astra.anblicks.pdca.service.periodLocalService periodLocalService;
	@BeanReference(type = periodPersistence.class)
	protected periodPersistence periodPersistence;
	@BeanReference(type = com.astra.anblicks.pdca.service.tradingProfitLocalService.class)
	protected com.astra.anblicks.pdca.service.tradingProfitLocalService tradingProfitLocalService;
	@BeanReference(type = tradingProfitPersistence.class)
	protected tradingProfitPersistence tradingProfitPersistence;
	@BeanReference(type = com.astra.anblicks.pdca.service.typeLocalService.class)
	protected com.astra.anblicks.pdca.service.typeLocalService typeLocalService;
	@BeanReference(type = typePersistence.class)
	protected typePersistence typePersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}