/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.anblicks.pdca.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.astra.anblicks.pdca.model.AstraPdca_Year;
import com.astra.anblicks.pdca.model.AstraPdca_YearModel;
import com.astra.anblicks.pdca.model.AstraPdca_YearSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the AstraPdca_Year service. Represents a row in the &quot;pdca_astrapdca_year&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link AstraPdca_YearModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AstraPdca_YearImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AstraPdca_YearImpl
 * @see AstraPdca_Year
 * @see AstraPdca_YearModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class AstraPdca_YearModelImpl extends BaseModelImpl<AstraPdca_Year>
	implements AstraPdca_YearModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a astra pdca_ year model instance should use the {@link AstraPdca_Year} interface instead.
	 */
	public static final String TABLE_NAME = "pdca_astrapdca_year";
	public static final Object[][] TABLE_COLUMNS = {
			{ "YearId", Types.BIGINT },
			{ "YearId_Company", Types.BIGINT },
			{ "Year", Types.BIGINT },
			{ "SiteId", Types.BIGINT },
			{ "CreateDate", Types.TIMESTAMP },
			{ "CreatedBy", Types.VARCHAR },
			{ "ModifiedDate", Types.TIMESTAMP },
			{ "ModifiedBy", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("YearId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("YearId_Company", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("Year", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("SiteId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("CreateDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table pdca_astrapdca_year (YearId LONG not null primary key,YearId_Company LONG,Year LONG,SiteId LONG,CreateDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table pdca_astrapdca_year";
	public static final String ORDER_BY_JPQL = " ORDER BY astraPdca_Year.YearId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY pdca_astrapdca_year.YearId ASC";
	public static final String DATA_SOURCE = "pdcaSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.astra.anblicks.pdca.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.astra.anblicks.pdca.model.AstraPdca_Year"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.astra.anblicks.pdca.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.astra.anblicks.pdca.model.AstraPdca_Year"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static AstraPdca_Year toModel(AstraPdca_YearSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		AstraPdca_Year model = new AstraPdca_YearImpl();

		model.setYearId(soapModel.getYearId());
		model.setYearId_Company(soapModel.getYearId_Company());
		model.setYear(soapModel.getYear());
		model.setSiteId(soapModel.getSiteId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setCreatedBy(soapModel.getCreatedBy());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setModifiedBy(soapModel.getModifiedBy());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<AstraPdca_Year> toModels(AstraPdca_YearSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<AstraPdca_Year> models = new ArrayList<AstraPdca_Year>(soapModels.length);

		for (AstraPdca_YearSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.astra.anblicks.pdca.service.util.ServiceProps.get(
				"lock.expiration.time.com.astra.anblicks.pdca.model.AstraPdca_Year"));

	public AstraPdca_YearModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _YearId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setYearId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _YearId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AstraPdca_Year.class;
	}

	@Override
	public String getModelClassName() {
		return AstraPdca_Year.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("YearId", getYearId());
		attributes.put("YearId_Company", getYearId_Company());
		attributes.put("Year", getYear());
		attributes.put("SiteId", getSiteId());
		attributes.put("CreateDate", getCreateDate());
		attributes.put("CreatedBy", getCreatedBy());
		attributes.put("ModifiedDate", getModifiedDate());
		attributes.put("ModifiedBy", getModifiedBy());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long YearId = (Long)attributes.get("YearId");

		if (YearId != null) {
			setYearId(YearId);
		}

		Long YearId_Company = (Long)attributes.get("YearId_Company");

		if (YearId_Company != null) {
			setYearId_Company(YearId_Company);
		}

		Long Year = (Long)attributes.get("Year");

		if (Year != null) {
			setYear(Year);
		}

		Long SiteId = (Long)attributes.get("SiteId");

		if (SiteId != null) {
			setSiteId(SiteId);
		}

		Date CreateDate = (Date)attributes.get("CreateDate");

		if (CreateDate != null) {
			setCreateDate(CreateDate);
		}

		String CreatedBy = (String)attributes.get("CreatedBy");

		if (CreatedBy != null) {
			setCreatedBy(CreatedBy);
		}

		Date ModifiedDate = (Date)attributes.get("ModifiedDate");

		if (ModifiedDate != null) {
			setModifiedDate(ModifiedDate);
		}

		String ModifiedBy = (String)attributes.get("ModifiedBy");

		if (ModifiedBy != null) {
			setModifiedBy(ModifiedBy);
		}
	}

	@JSON
	@Override
	public long getYearId() {
		return _YearId;
	}

	@Override
	public void setYearId(long YearId) {
		_YearId = YearId;
	}

	@JSON
	@Override
	public long getYearId_Company() {
		return _YearId_Company;
	}

	@Override
	public void setYearId_Company(long YearId_Company) {
		_YearId_Company = YearId_Company;
	}

	@JSON
	@Override
	public long getYear() {
		return _Year;
	}

	@Override
	public void setYear(long Year) {
		_Year = Year;
	}

	@JSON
	@Override
	public long getSiteId() {
		return _SiteId;
	}

	@Override
	public void setSiteId(long SiteId) {
		_SiteId = SiteId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _CreateDate;
	}

	@Override
	public void setCreateDate(Date CreateDate) {
		_CreateDate = CreateDate;
	}

	@JSON
	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		_CreatedBy = CreatedBy;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		_ModifiedDate = ModifiedDate;
	}

	@JSON
	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		_ModifiedBy = ModifiedBy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			AstraPdca_Year.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AstraPdca_Year toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (AstraPdca_Year)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AstraPdca_YearImpl astraPdca_YearImpl = new AstraPdca_YearImpl();

		astraPdca_YearImpl.setYearId(getYearId());
		astraPdca_YearImpl.setYearId_Company(getYearId_Company());
		astraPdca_YearImpl.setYear(getYear());
		astraPdca_YearImpl.setSiteId(getSiteId());
		astraPdca_YearImpl.setCreateDate(getCreateDate());
		astraPdca_YearImpl.setCreatedBy(getCreatedBy());
		astraPdca_YearImpl.setModifiedDate(getModifiedDate());
		astraPdca_YearImpl.setModifiedBy(getModifiedBy());

		astraPdca_YearImpl.resetOriginalValues();

		return astraPdca_YearImpl;
	}

	@Override
	public int compareTo(AstraPdca_Year astraPdca_Year) {
		long primaryKey = astraPdca_Year.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AstraPdca_Year)) {
			return false;
		}

		AstraPdca_Year astraPdca_Year = (AstraPdca_Year)obj;

		long primaryKey = astraPdca_Year.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<AstraPdca_Year> toCacheModel() {
		AstraPdca_YearCacheModel astraPdca_YearCacheModel = new AstraPdca_YearCacheModel();

		astraPdca_YearCacheModel.YearId = getYearId();

		astraPdca_YearCacheModel.YearId_Company = getYearId_Company();

		astraPdca_YearCacheModel.Year = getYear();

		astraPdca_YearCacheModel.SiteId = getSiteId();

		Date CreateDate = getCreateDate();

		if (CreateDate != null) {
			astraPdca_YearCacheModel.CreateDate = CreateDate.getTime();
		}
		else {
			astraPdca_YearCacheModel.CreateDate = Long.MIN_VALUE;
		}

		astraPdca_YearCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = astraPdca_YearCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			astraPdca_YearCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			astraPdca_YearCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			astraPdca_YearCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		astraPdca_YearCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = astraPdca_YearCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			astraPdca_YearCacheModel.ModifiedBy = null;
		}

		return astraPdca_YearCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{YearId=");
		sb.append(getYearId());
		sb.append(", YearId_Company=");
		sb.append(getYearId_Company());
		sb.append(", Year=");
		sb.append(getYear());
		sb.append(", SiteId=");
		sb.append(getSiteId());
		sb.append(", CreateDate=");
		sb.append(getCreateDate());
		sb.append(", CreatedBy=");
		sb.append(getCreatedBy());
		sb.append(", ModifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", ModifiedBy=");
		sb.append(getModifiedBy());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.astra.anblicks.pdca.model.AstraPdca_Year");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>YearId</column-name><column-value><![CDATA[");
		sb.append(getYearId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>YearId_Company</column-name><column-value><![CDATA[");
		sb.append(getYearId_Company());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Year</column-name><column-value><![CDATA[");
		sb.append(getYear());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SiteId</column-name><column-value><![CDATA[");
		sb.append(getSiteId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CreateDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CreatedBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ModifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ModifiedBy</column-name><column-value><![CDATA[");
		sb.append(getModifiedBy());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = AstraPdca_Year.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			AstraPdca_Year.class
		};
	private long _YearId;
	private long _YearId_Company;
	private long _Year;
	private long _SiteId;
	private Date _CreateDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;
	private AstraPdca_Year _escapedModel;
}