/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.anblicks.pdca.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.astra.anblicks.pdca.model.AstraPdca_CompanyData;
import com.astra.anblicks.pdca.model.AstraPdca_CompanyDataModel;
import com.astra.anblicks.pdca.model.AstraPdca_CompanyDataSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the AstraPdca_CompanyData service. Represents a row in the &quot;pdca_astrapdca_companydata&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link AstraPdca_CompanyDataModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AstraPdca_CompanyDataImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AstraPdca_CompanyDataImpl
 * @see AstraPdca_CompanyData
 * @see AstraPdca_CompanyDataModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class AstraPdca_CompanyDataModelImpl extends BaseModelImpl<AstraPdca_CompanyData>
	implements AstraPdca_CompanyDataModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a astra pdca_ company data model instance should use the {@link AstraPdca_CompanyData} interface instead.
	 */
	public static final String TABLE_NAME = "pdca_astrapdca_companydata";
	public static final Object[][] TABLE_COLUMNS = {
			{ "companyId", Types.BIGINT },
			{ "CompanyCode", Types.VARCHAR },
			{ "CompanyName", Types.VARCHAR },
			{ "GroupName", Types.VARCHAR },
			{ "DIC", Types.VARCHAR },
			{ "DICINITIAL", Types.VARCHAR },
			{ "LEFTUP", Types.VARCHAR },
			{ "LEFTUPTITLE", Types.VARCHAR },
			{ "LEFTUPCOMPANY", Types.VARCHAR },
			{ "LEFTBOTTOM", Types.VARCHAR },
			{ "LEFTBOTTOMTITLE", Types.VARCHAR },
			{ "LEFTBOTTOMCOMPANY", Types.VARCHAR },
			{ "MIDUP", Types.VARCHAR },
			{ "MIDUPTITLE", Types.VARCHAR },
			{ "MIDUPCOMPANY", Types.VARCHAR },
			{ "MIDBOTTOM", Types.VARCHAR },
			{ "MIDBOTTOMTITLE", Types.VARCHAR },
			{ "MIDBOTTOMCOMPANY", Types.VARCHAR },
			{ "RIGHTUP", Types.VARCHAR },
			{ "RIGHTUPTITLE", Types.VARCHAR },
			{ "RIGHTUPCOMPANY", Types.VARCHAR },
			{ "RIGHTBOTTOM", Types.VARCHAR },
			{ "RIGHTBOTTOMTITLE", Types.VARCHAR },
			{ "RIGHTBOTTOMCOMPANY", Types.VARCHAR },
			{ "ModuleId", Types.BIGINT },
			{ "YearId", Types.BIGINT },
			{ "CheckFlag", Types.VARCHAR },
			{ "SiteId", Types.BIGINT },
			{ "CreateDate", Types.TIMESTAMP },
			{ "CreatedBy", Types.VARCHAR },
			{ "ModifiedDate", Types.TIMESTAMP },
			{ "ModifiedBy", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("CompanyCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CompanyName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("GroupName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DIC", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DICINITIAL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("LEFTUP", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("LEFTUPTITLE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("LEFTUPCOMPANY", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("LEFTBOTTOM", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("LEFTBOTTOMTITLE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("LEFTBOTTOMCOMPANY", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("MIDUP", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("MIDUPTITLE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("MIDUPCOMPANY", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("MIDBOTTOM", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("MIDBOTTOMTITLE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("MIDBOTTOMCOMPANY", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RIGHTUP", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RIGHTUPTITLE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RIGHTUPCOMPANY", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RIGHTBOTTOM", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RIGHTBOTTOMTITLE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("RIGHTBOTTOMCOMPANY", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModuleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("YearId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("CheckFlag", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("SiteId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("CreateDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table pdca_astrapdca_companydata (companyId LONG not null primary key,CompanyCode VARCHAR(75) null,CompanyName VARCHAR(75) null,GroupName VARCHAR(75) null,DIC VARCHAR(75) null,DICINITIAL VARCHAR(75) null,LEFTUP VARCHAR(75) null,LEFTUPTITLE VARCHAR(75) null,LEFTUPCOMPANY VARCHAR(75) null,LEFTBOTTOM VARCHAR(75) null,LEFTBOTTOMTITLE VARCHAR(75) null,LEFTBOTTOMCOMPANY VARCHAR(75) null,MIDUP VARCHAR(75) null,MIDUPTITLE VARCHAR(75) null,MIDUPCOMPANY VARCHAR(75) null,MIDBOTTOM VARCHAR(75) null,MIDBOTTOMTITLE VARCHAR(75) null,MIDBOTTOMCOMPANY VARCHAR(75) null,RIGHTUP VARCHAR(75) null,RIGHTUPTITLE VARCHAR(75) null,RIGHTUPCOMPANY VARCHAR(75) null,RIGHTBOTTOM VARCHAR(75) null,RIGHTBOTTOMTITLE VARCHAR(75) null,RIGHTBOTTOMCOMPANY VARCHAR(75) null,ModuleId LONG,YearId LONG,CheckFlag VARCHAR(75) null,SiteId LONG,CreateDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table pdca_astrapdca_companydata";
	public static final String ORDER_BY_JPQL = " ORDER BY astraPdca_CompanyData.companyId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY pdca_astrapdca_companydata.companyId ASC";
	public static final String DATA_SOURCE = "pdcaSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.astra.anblicks.pdca.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.astra.anblicks.pdca.model.AstraPdca_CompanyData"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.astra.anblicks.pdca.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.astra.anblicks.pdca.model.AstraPdca_CompanyData"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static AstraPdca_CompanyData toModel(
		AstraPdca_CompanyDataSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		AstraPdca_CompanyData model = new AstraPdca_CompanyDataImpl();

		model.setCompanyId(soapModel.getCompanyId());
		model.setCompanyCode(soapModel.getCompanyCode());
		model.setCompanyName(soapModel.getCompanyName());
		model.setGroupName(soapModel.getGroupName());
		model.setDIC(soapModel.getDIC());
		model.setDICINITIAL(soapModel.getDICINITIAL());
		model.setLEFTUP(soapModel.getLEFTUP());
		model.setLEFTUPTITLE(soapModel.getLEFTUPTITLE());
		model.setLEFTUPCOMPANY(soapModel.getLEFTUPCOMPANY());
		model.setLEFTBOTTOM(soapModel.getLEFTBOTTOM());
		model.setLEFTBOTTOMTITLE(soapModel.getLEFTBOTTOMTITLE());
		model.setLEFTBOTTOMCOMPANY(soapModel.getLEFTBOTTOMCOMPANY());
		model.setMIDUP(soapModel.getMIDUP());
		model.setMIDUPTITLE(soapModel.getMIDUPTITLE());
		model.setMIDUPCOMPANY(soapModel.getMIDUPCOMPANY());
		model.setMIDBOTTOM(soapModel.getMIDBOTTOM());
		model.setMIDBOTTOMTITLE(soapModel.getMIDBOTTOMTITLE());
		model.setMIDBOTTOMCOMPANY(soapModel.getMIDBOTTOMCOMPANY());
		model.setRIGHTUP(soapModel.getRIGHTUP());
		model.setRIGHTUPTITLE(soapModel.getRIGHTUPTITLE());
		model.setRIGHTUPCOMPANY(soapModel.getRIGHTUPCOMPANY());
		model.setRIGHTBOTTOM(soapModel.getRIGHTBOTTOM());
		model.setRIGHTBOTTOMTITLE(soapModel.getRIGHTBOTTOMTITLE());
		model.setRIGHTBOTTOMCOMPANY(soapModel.getRIGHTBOTTOMCOMPANY());
		model.setModuleId(soapModel.getModuleId());
		model.setYearId(soapModel.getYearId());
		model.setCheckFlag(soapModel.getCheckFlag());
		model.setSiteId(soapModel.getSiteId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setCreatedBy(soapModel.getCreatedBy());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setModifiedBy(soapModel.getModifiedBy());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<AstraPdca_CompanyData> toModels(
		AstraPdca_CompanyDataSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<AstraPdca_CompanyData> models = new ArrayList<AstraPdca_CompanyData>(soapModels.length);

		for (AstraPdca_CompanyDataSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.astra.anblicks.pdca.service.util.ServiceProps.get(
				"lock.expiration.time.com.astra.anblicks.pdca.model.AstraPdca_CompanyData"));

	public AstraPdca_CompanyDataModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _companyId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCompanyId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _companyId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AstraPdca_CompanyData.class;
	}

	@Override
	public String getModelClassName() {
		return AstraPdca_CompanyData.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("companyId", getCompanyId());
		attributes.put("CompanyCode", getCompanyCode());
		attributes.put("CompanyName", getCompanyName());
		attributes.put("GroupName", getGroupName());
		attributes.put("DIC", getDIC());
		attributes.put("DICINITIAL", getDICINITIAL());
		attributes.put("LEFTUP", getLEFTUP());
		attributes.put("LEFTUPTITLE", getLEFTUPTITLE());
		attributes.put("LEFTUPCOMPANY", getLEFTUPCOMPANY());
		attributes.put("LEFTBOTTOM", getLEFTBOTTOM());
		attributes.put("LEFTBOTTOMTITLE", getLEFTBOTTOMTITLE());
		attributes.put("LEFTBOTTOMCOMPANY", getLEFTBOTTOMCOMPANY());
		attributes.put("MIDUP", getMIDUP());
		attributes.put("MIDUPTITLE", getMIDUPTITLE());
		attributes.put("MIDUPCOMPANY", getMIDUPCOMPANY());
		attributes.put("MIDBOTTOM", getMIDBOTTOM());
		attributes.put("MIDBOTTOMTITLE", getMIDBOTTOMTITLE());
		attributes.put("MIDBOTTOMCOMPANY", getMIDBOTTOMCOMPANY());
		attributes.put("RIGHTUP", getRIGHTUP());
		attributes.put("RIGHTUPTITLE", getRIGHTUPTITLE());
		attributes.put("RIGHTUPCOMPANY", getRIGHTUPCOMPANY());
		attributes.put("RIGHTBOTTOM", getRIGHTBOTTOM());
		attributes.put("RIGHTBOTTOMTITLE", getRIGHTBOTTOMTITLE());
		attributes.put("RIGHTBOTTOMCOMPANY", getRIGHTBOTTOMCOMPANY());
		attributes.put("ModuleId", getModuleId());
		attributes.put("YearId", getYearId());
		attributes.put("CheckFlag", getCheckFlag());
		attributes.put("SiteId", getSiteId());
		attributes.put("CreateDate", getCreateDate());
		attributes.put("CreatedBy", getCreatedBy());
		attributes.put("ModifiedDate", getModifiedDate());
		attributes.put("ModifiedBy", getModifiedBy());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		String CompanyCode = (String)attributes.get("CompanyCode");

		if (CompanyCode != null) {
			setCompanyCode(CompanyCode);
		}

		String CompanyName = (String)attributes.get("CompanyName");

		if (CompanyName != null) {
			setCompanyName(CompanyName);
		}

		String GroupName = (String)attributes.get("GroupName");

		if (GroupName != null) {
			setGroupName(GroupName);
		}

		String DIC = (String)attributes.get("DIC");

		if (DIC != null) {
			setDIC(DIC);
		}

		String DICINITIAL = (String)attributes.get("DICINITIAL");

		if (DICINITIAL != null) {
			setDICINITIAL(DICINITIAL);
		}

		String LEFTUP = (String)attributes.get("LEFTUP");

		if (LEFTUP != null) {
			setLEFTUP(LEFTUP);
		}

		String LEFTUPTITLE = (String)attributes.get("LEFTUPTITLE");

		if (LEFTUPTITLE != null) {
			setLEFTUPTITLE(LEFTUPTITLE);
		}

		String LEFTUPCOMPANY = (String)attributes.get("LEFTUPCOMPANY");

		if (LEFTUPCOMPANY != null) {
			setLEFTUPCOMPANY(LEFTUPCOMPANY);
		}

		String LEFTBOTTOM = (String)attributes.get("LEFTBOTTOM");

		if (LEFTBOTTOM != null) {
			setLEFTBOTTOM(LEFTBOTTOM);
		}

		String LEFTBOTTOMTITLE = (String)attributes.get("LEFTBOTTOMTITLE");

		if (LEFTBOTTOMTITLE != null) {
			setLEFTBOTTOMTITLE(LEFTBOTTOMTITLE);
		}

		String LEFTBOTTOMCOMPANY = (String)attributes.get("LEFTBOTTOMCOMPANY");

		if (LEFTBOTTOMCOMPANY != null) {
			setLEFTBOTTOMCOMPANY(LEFTBOTTOMCOMPANY);
		}

		String MIDUP = (String)attributes.get("MIDUP");

		if (MIDUP != null) {
			setMIDUP(MIDUP);
		}

		String MIDUPTITLE = (String)attributes.get("MIDUPTITLE");

		if (MIDUPTITLE != null) {
			setMIDUPTITLE(MIDUPTITLE);
		}

		String MIDUPCOMPANY = (String)attributes.get("MIDUPCOMPANY");

		if (MIDUPCOMPANY != null) {
			setMIDUPCOMPANY(MIDUPCOMPANY);
		}

		String MIDBOTTOM = (String)attributes.get("MIDBOTTOM");

		if (MIDBOTTOM != null) {
			setMIDBOTTOM(MIDBOTTOM);
		}

		String MIDBOTTOMTITLE = (String)attributes.get("MIDBOTTOMTITLE");

		if (MIDBOTTOMTITLE != null) {
			setMIDBOTTOMTITLE(MIDBOTTOMTITLE);
		}

		String MIDBOTTOMCOMPANY = (String)attributes.get("MIDBOTTOMCOMPANY");

		if (MIDBOTTOMCOMPANY != null) {
			setMIDBOTTOMCOMPANY(MIDBOTTOMCOMPANY);
		}

		String RIGHTUP = (String)attributes.get("RIGHTUP");

		if (RIGHTUP != null) {
			setRIGHTUP(RIGHTUP);
		}

		String RIGHTUPTITLE = (String)attributes.get("RIGHTUPTITLE");

		if (RIGHTUPTITLE != null) {
			setRIGHTUPTITLE(RIGHTUPTITLE);
		}

		String RIGHTUPCOMPANY = (String)attributes.get("RIGHTUPCOMPANY");

		if (RIGHTUPCOMPANY != null) {
			setRIGHTUPCOMPANY(RIGHTUPCOMPANY);
		}

		String RIGHTBOTTOM = (String)attributes.get("RIGHTBOTTOM");

		if (RIGHTBOTTOM != null) {
			setRIGHTBOTTOM(RIGHTBOTTOM);
		}

		String RIGHTBOTTOMTITLE = (String)attributes.get("RIGHTBOTTOMTITLE");

		if (RIGHTBOTTOMTITLE != null) {
			setRIGHTBOTTOMTITLE(RIGHTBOTTOMTITLE);
		}

		String RIGHTBOTTOMCOMPANY = (String)attributes.get("RIGHTBOTTOMCOMPANY");

		if (RIGHTBOTTOMCOMPANY != null) {
			setRIGHTBOTTOMCOMPANY(RIGHTBOTTOMCOMPANY);
		}

		Long ModuleId = (Long)attributes.get("ModuleId");

		if (ModuleId != null) {
			setModuleId(ModuleId);
		}

		Long YearId = (Long)attributes.get("YearId");

		if (YearId != null) {
			setYearId(YearId);
		}

		String CheckFlag = (String)attributes.get("CheckFlag");

		if (CheckFlag != null) {
			setCheckFlag(CheckFlag);
		}

		Long SiteId = (Long)attributes.get("SiteId");

		if (SiteId != null) {
			setSiteId(SiteId);
		}

		Date CreateDate = (Date)attributes.get("CreateDate");

		if (CreateDate != null) {
			setCreateDate(CreateDate);
		}

		String CreatedBy = (String)attributes.get("CreatedBy");

		if (CreatedBy != null) {
			setCreatedBy(CreatedBy);
		}

		Date ModifiedDate = (Date)attributes.get("ModifiedDate");

		if (ModifiedDate != null) {
			setModifiedDate(ModifiedDate);
		}

		String ModifiedBy = (String)attributes.get("ModifiedBy");

		if (ModifiedBy != null) {
			setModifiedBy(ModifiedBy);
		}
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public String getCompanyCode() {
		if (_CompanyCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _CompanyCode;
		}
	}

	@Override
	public void setCompanyCode(String CompanyCode) {
		_CompanyCode = CompanyCode;
	}

	@JSON
	@Override
	public String getCompanyName() {
		if (_CompanyName == null) {
			return StringPool.BLANK;
		}
		else {
			return _CompanyName;
		}
	}

	@Override
	public void setCompanyName(String CompanyName) {
		_CompanyName = CompanyName;
	}

	@JSON
	@Override
	public String getGroupName() {
		if (_GroupName == null) {
			return StringPool.BLANK;
		}
		else {
			return _GroupName;
		}
	}

	@Override
	public void setGroupName(String GroupName) {
		_GroupName = GroupName;
	}

	@JSON
	@Override
	public String getDIC() {
		if (_DIC == null) {
			return StringPool.BLANK;
		}
		else {
			return _DIC;
		}
	}

	@Override
	public void setDIC(String DIC) {
		_DIC = DIC;
	}

	@JSON
	@Override
	public String getDICINITIAL() {
		if (_DICINITIAL == null) {
			return StringPool.BLANK;
		}
		else {
			return _DICINITIAL;
		}
	}

	@Override
	public void setDICINITIAL(String DICINITIAL) {
		_DICINITIAL = DICINITIAL;
	}

	@JSON
	@Override
	public String getLEFTUP() {
		if (_LEFTUP == null) {
			return StringPool.BLANK;
		}
		else {
			return _LEFTUP;
		}
	}

	@Override
	public void setLEFTUP(String LEFTUP) {
		_LEFTUP = LEFTUP;
	}

	@JSON
	@Override
	public String getLEFTUPTITLE() {
		if (_LEFTUPTITLE == null) {
			return StringPool.BLANK;
		}
		else {
			return _LEFTUPTITLE;
		}
	}

	@Override
	public void setLEFTUPTITLE(String LEFTUPTITLE) {
		_LEFTUPTITLE = LEFTUPTITLE;
	}

	@JSON
	@Override
	public String getLEFTUPCOMPANY() {
		if (_LEFTUPCOMPANY == null) {
			return StringPool.BLANK;
		}
		else {
			return _LEFTUPCOMPANY;
		}
	}

	@Override
	public void setLEFTUPCOMPANY(String LEFTUPCOMPANY) {
		_LEFTUPCOMPANY = LEFTUPCOMPANY;
	}

	@JSON
	@Override
	public String getLEFTBOTTOM() {
		if (_LEFTBOTTOM == null) {
			return StringPool.BLANK;
		}
		else {
			return _LEFTBOTTOM;
		}
	}

	@Override
	public void setLEFTBOTTOM(String LEFTBOTTOM) {
		_LEFTBOTTOM = LEFTBOTTOM;
	}

	@JSON
	@Override
	public String getLEFTBOTTOMTITLE() {
		if (_LEFTBOTTOMTITLE == null) {
			return StringPool.BLANK;
		}
		else {
			return _LEFTBOTTOMTITLE;
		}
	}

	@Override
	public void setLEFTBOTTOMTITLE(String LEFTBOTTOMTITLE) {
		_LEFTBOTTOMTITLE = LEFTBOTTOMTITLE;
	}

	@JSON
	@Override
	public String getLEFTBOTTOMCOMPANY() {
		if (_LEFTBOTTOMCOMPANY == null) {
			return StringPool.BLANK;
		}
		else {
			return _LEFTBOTTOMCOMPANY;
		}
	}

	@Override
	public void setLEFTBOTTOMCOMPANY(String LEFTBOTTOMCOMPANY) {
		_LEFTBOTTOMCOMPANY = LEFTBOTTOMCOMPANY;
	}

	@JSON
	@Override
	public String getMIDUP() {
		if (_MIDUP == null) {
			return StringPool.BLANK;
		}
		else {
			return _MIDUP;
		}
	}

	@Override
	public void setMIDUP(String MIDUP) {
		_MIDUP = MIDUP;
	}

	@JSON
	@Override
	public String getMIDUPTITLE() {
		if (_MIDUPTITLE == null) {
			return StringPool.BLANK;
		}
		else {
			return _MIDUPTITLE;
		}
	}

	@Override
	public void setMIDUPTITLE(String MIDUPTITLE) {
		_MIDUPTITLE = MIDUPTITLE;
	}

	@JSON
	@Override
	public String getMIDUPCOMPANY() {
		if (_MIDUPCOMPANY == null) {
			return StringPool.BLANK;
		}
		else {
			return _MIDUPCOMPANY;
		}
	}

	@Override
	public void setMIDUPCOMPANY(String MIDUPCOMPANY) {
		_MIDUPCOMPANY = MIDUPCOMPANY;
	}

	@JSON
	@Override
	public String getMIDBOTTOM() {
		if (_MIDBOTTOM == null) {
			return StringPool.BLANK;
		}
		else {
			return _MIDBOTTOM;
		}
	}

	@Override
	public void setMIDBOTTOM(String MIDBOTTOM) {
		_MIDBOTTOM = MIDBOTTOM;
	}

	@JSON
	@Override
	public String getMIDBOTTOMTITLE() {
		if (_MIDBOTTOMTITLE == null) {
			return StringPool.BLANK;
		}
		else {
			return _MIDBOTTOMTITLE;
		}
	}

	@Override
	public void setMIDBOTTOMTITLE(String MIDBOTTOMTITLE) {
		_MIDBOTTOMTITLE = MIDBOTTOMTITLE;
	}

	@JSON
	@Override
	public String getMIDBOTTOMCOMPANY() {
		if (_MIDBOTTOMCOMPANY == null) {
			return StringPool.BLANK;
		}
		else {
			return _MIDBOTTOMCOMPANY;
		}
	}

	@Override
	public void setMIDBOTTOMCOMPANY(String MIDBOTTOMCOMPANY) {
		_MIDBOTTOMCOMPANY = MIDBOTTOMCOMPANY;
	}

	@JSON
	@Override
	public String getRIGHTUP() {
		if (_RIGHTUP == null) {
			return StringPool.BLANK;
		}
		else {
			return _RIGHTUP;
		}
	}

	@Override
	public void setRIGHTUP(String RIGHTUP) {
		_RIGHTUP = RIGHTUP;
	}

	@JSON
	@Override
	public String getRIGHTUPTITLE() {
		if (_RIGHTUPTITLE == null) {
			return StringPool.BLANK;
		}
		else {
			return _RIGHTUPTITLE;
		}
	}

	@Override
	public void setRIGHTUPTITLE(String RIGHTUPTITLE) {
		_RIGHTUPTITLE = RIGHTUPTITLE;
	}

	@JSON
	@Override
	public String getRIGHTUPCOMPANY() {
		if (_RIGHTUPCOMPANY == null) {
			return StringPool.BLANK;
		}
		else {
			return _RIGHTUPCOMPANY;
		}
	}

	@Override
	public void setRIGHTUPCOMPANY(String RIGHTUPCOMPANY) {
		_RIGHTUPCOMPANY = RIGHTUPCOMPANY;
	}

	@JSON
	@Override
	public String getRIGHTBOTTOM() {
		if (_RIGHTBOTTOM == null) {
			return StringPool.BLANK;
		}
		else {
			return _RIGHTBOTTOM;
		}
	}

	@Override
	public void setRIGHTBOTTOM(String RIGHTBOTTOM) {
		_RIGHTBOTTOM = RIGHTBOTTOM;
	}

	@JSON
	@Override
	public String getRIGHTBOTTOMTITLE() {
		if (_RIGHTBOTTOMTITLE == null) {
			return StringPool.BLANK;
		}
		else {
			return _RIGHTBOTTOMTITLE;
		}
	}

	@Override
	public void setRIGHTBOTTOMTITLE(String RIGHTBOTTOMTITLE) {
		_RIGHTBOTTOMTITLE = RIGHTBOTTOMTITLE;
	}

	@JSON
	@Override
	public String getRIGHTBOTTOMCOMPANY() {
		if (_RIGHTBOTTOMCOMPANY == null) {
			return StringPool.BLANK;
		}
		else {
			return _RIGHTBOTTOMCOMPANY;
		}
	}

	@Override
	public void setRIGHTBOTTOMCOMPANY(String RIGHTBOTTOMCOMPANY) {
		_RIGHTBOTTOMCOMPANY = RIGHTBOTTOMCOMPANY;
	}

	@JSON
	@Override
	public long getModuleId() {
		return _ModuleId;
	}

	@Override
	public void setModuleId(long ModuleId) {
		_ModuleId = ModuleId;
	}

	@JSON
	@Override
	public long getYearId() {
		return _YearId;
	}

	@Override
	public void setYearId(long YearId) {
		_YearId = YearId;
	}

	@JSON
	@Override
	public String getCheckFlag() {
		if (_CheckFlag == null) {
			return StringPool.BLANK;
		}
		else {
			return _CheckFlag;
		}
	}

	@Override
	public void setCheckFlag(String CheckFlag) {
		_CheckFlag = CheckFlag;
	}

	@JSON
	@Override
	public long getSiteId() {
		return _SiteId;
	}

	@Override
	public void setSiteId(long SiteId) {
		_SiteId = SiteId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _CreateDate;
	}

	@Override
	public void setCreateDate(Date CreateDate) {
		_CreateDate = CreateDate;
	}

	@JSON
	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		_CreatedBy = CreatedBy;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		_ModifiedDate = ModifiedDate;
	}

	@JSON
	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		_ModifiedBy = ModifiedBy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			AstraPdca_CompanyData.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AstraPdca_CompanyData toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (AstraPdca_CompanyData)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AstraPdca_CompanyDataImpl astraPdca_CompanyDataImpl = new AstraPdca_CompanyDataImpl();

		astraPdca_CompanyDataImpl.setCompanyId(getCompanyId());
		astraPdca_CompanyDataImpl.setCompanyCode(getCompanyCode());
		astraPdca_CompanyDataImpl.setCompanyName(getCompanyName());
		astraPdca_CompanyDataImpl.setGroupName(getGroupName());
		astraPdca_CompanyDataImpl.setDIC(getDIC());
		astraPdca_CompanyDataImpl.setDICINITIAL(getDICINITIAL());
		astraPdca_CompanyDataImpl.setLEFTUP(getLEFTUP());
		astraPdca_CompanyDataImpl.setLEFTUPTITLE(getLEFTUPTITLE());
		astraPdca_CompanyDataImpl.setLEFTUPCOMPANY(getLEFTUPCOMPANY());
		astraPdca_CompanyDataImpl.setLEFTBOTTOM(getLEFTBOTTOM());
		astraPdca_CompanyDataImpl.setLEFTBOTTOMTITLE(getLEFTBOTTOMTITLE());
		astraPdca_CompanyDataImpl.setLEFTBOTTOMCOMPANY(getLEFTBOTTOMCOMPANY());
		astraPdca_CompanyDataImpl.setMIDUP(getMIDUP());
		astraPdca_CompanyDataImpl.setMIDUPTITLE(getMIDUPTITLE());
		astraPdca_CompanyDataImpl.setMIDUPCOMPANY(getMIDUPCOMPANY());
		astraPdca_CompanyDataImpl.setMIDBOTTOM(getMIDBOTTOM());
		astraPdca_CompanyDataImpl.setMIDBOTTOMTITLE(getMIDBOTTOMTITLE());
		astraPdca_CompanyDataImpl.setMIDBOTTOMCOMPANY(getMIDBOTTOMCOMPANY());
		astraPdca_CompanyDataImpl.setRIGHTUP(getRIGHTUP());
		astraPdca_CompanyDataImpl.setRIGHTUPTITLE(getRIGHTUPTITLE());
		astraPdca_CompanyDataImpl.setRIGHTUPCOMPANY(getRIGHTUPCOMPANY());
		astraPdca_CompanyDataImpl.setRIGHTBOTTOM(getRIGHTBOTTOM());
		astraPdca_CompanyDataImpl.setRIGHTBOTTOMTITLE(getRIGHTBOTTOMTITLE());
		astraPdca_CompanyDataImpl.setRIGHTBOTTOMCOMPANY(getRIGHTBOTTOMCOMPANY());
		astraPdca_CompanyDataImpl.setModuleId(getModuleId());
		astraPdca_CompanyDataImpl.setYearId(getYearId());
		astraPdca_CompanyDataImpl.setCheckFlag(getCheckFlag());
		astraPdca_CompanyDataImpl.setSiteId(getSiteId());
		astraPdca_CompanyDataImpl.setCreateDate(getCreateDate());
		astraPdca_CompanyDataImpl.setCreatedBy(getCreatedBy());
		astraPdca_CompanyDataImpl.setModifiedDate(getModifiedDate());
		astraPdca_CompanyDataImpl.setModifiedBy(getModifiedBy());

		astraPdca_CompanyDataImpl.resetOriginalValues();

		return astraPdca_CompanyDataImpl;
	}

	@Override
	public int compareTo(AstraPdca_CompanyData astraPdca_CompanyData) {
		long primaryKey = astraPdca_CompanyData.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AstraPdca_CompanyData)) {
			return false;
		}

		AstraPdca_CompanyData astraPdca_CompanyData = (AstraPdca_CompanyData)obj;

		long primaryKey = astraPdca_CompanyData.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<AstraPdca_CompanyData> toCacheModel() {
		AstraPdca_CompanyDataCacheModel astraPdca_CompanyDataCacheModel = new AstraPdca_CompanyDataCacheModel();

		astraPdca_CompanyDataCacheModel.companyId = getCompanyId();

		astraPdca_CompanyDataCacheModel.CompanyCode = getCompanyCode();

		String CompanyCode = astraPdca_CompanyDataCacheModel.CompanyCode;

		if ((CompanyCode != null) && (CompanyCode.length() == 0)) {
			astraPdca_CompanyDataCacheModel.CompanyCode = null;
		}

		astraPdca_CompanyDataCacheModel.CompanyName = getCompanyName();

		String CompanyName = astraPdca_CompanyDataCacheModel.CompanyName;

		if ((CompanyName != null) && (CompanyName.length() == 0)) {
			astraPdca_CompanyDataCacheModel.CompanyName = null;
		}

		astraPdca_CompanyDataCacheModel.GroupName = getGroupName();

		String GroupName = astraPdca_CompanyDataCacheModel.GroupName;

		if ((GroupName != null) && (GroupName.length() == 0)) {
			astraPdca_CompanyDataCacheModel.GroupName = null;
		}

		astraPdca_CompanyDataCacheModel.DIC = getDIC();

		String DIC = astraPdca_CompanyDataCacheModel.DIC;

		if ((DIC != null) && (DIC.length() == 0)) {
			astraPdca_CompanyDataCacheModel.DIC = null;
		}

		astraPdca_CompanyDataCacheModel.DICINITIAL = getDICINITIAL();

		String DICINITIAL = astraPdca_CompanyDataCacheModel.DICINITIAL;

		if ((DICINITIAL != null) && (DICINITIAL.length() == 0)) {
			astraPdca_CompanyDataCacheModel.DICINITIAL = null;
		}

		astraPdca_CompanyDataCacheModel.LEFTUP = getLEFTUP();

		String LEFTUP = astraPdca_CompanyDataCacheModel.LEFTUP;

		if ((LEFTUP != null) && (LEFTUP.length() == 0)) {
			astraPdca_CompanyDataCacheModel.LEFTUP = null;
		}

		astraPdca_CompanyDataCacheModel.LEFTUPTITLE = getLEFTUPTITLE();

		String LEFTUPTITLE = astraPdca_CompanyDataCacheModel.LEFTUPTITLE;

		if ((LEFTUPTITLE != null) && (LEFTUPTITLE.length() == 0)) {
			astraPdca_CompanyDataCacheModel.LEFTUPTITLE = null;
		}

		astraPdca_CompanyDataCacheModel.LEFTUPCOMPANY = getLEFTUPCOMPANY();

		String LEFTUPCOMPANY = astraPdca_CompanyDataCacheModel.LEFTUPCOMPANY;

		if ((LEFTUPCOMPANY != null) && (LEFTUPCOMPANY.length() == 0)) {
			astraPdca_CompanyDataCacheModel.LEFTUPCOMPANY = null;
		}

		astraPdca_CompanyDataCacheModel.LEFTBOTTOM = getLEFTBOTTOM();

		String LEFTBOTTOM = astraPdca_CompanyDataCacheModel.LEFTBOTTOM;

		if ((LEFTBOTTOM != null) && (LEFTBOTTOM.length() == 0)) {
			astraPdca_CompanyDataCacheModel.LEFTBOTTOM = null;
		}

		astraPdca_CompanyDataCacheModel.LEFTBOTTOMTITLE = getLEFTBOTTOMTITLE();

		String LEFTBOTTOMTITLE = astraPdca_CompanyDataCacheModel.LEFTBOTTOMTITLE;

		if ((LEFTBOTTOMTITLE != null) && (LEFTBOTTOMTITLE.length() == 0)) {
			astraPdca_CompanyDataCacheModel.LEFTBOTTOMTITLE = null;
		}

		astraPdca_CompanyDataCacheModel.LEFTBOTTOMCOMPANY = getLEFTBOTTOMCOMPANY();

		String LEFTBOTTOMCOMPANY = astraPdca_CompanyDataCacheModel.LEFTBOTTOMCOMPANY;

		if ((LEFTBOTTOMCOMPANY != null) && (LEFTBOTTOMCOMPANY.length() == 0)) {
			astraPdca_CompanyDataCacheModel.LEFTBOTTOMCOMPANY = null;
		}

		astraPdca_CompanyDataCacheModel.MIDUP = getMIDUP();

		String MIDUP = astraPdca_CompanyDataCacheModel.MIDUP;

		if ((MIDUP != null) && (MIDUP.length() == 0)) {
			astraPdca_CompanyDataCacheModel.MIDUP = null;
		}

		astraPdca_CompanyDataCacheModel.MIDUPTITLE = getMIDUPTITLE();

		String MIDUPTITLE = astraPdca_CompanyDataCacheModel.MIDUPTITLE;

		if ((MIDUPTITLE != null) && (MIDUPTITLE.length() == 0)) {
			astraPdca_CompanyDataCacheModel.MIDUPTITLE = null;
		}

		astraPdca_CompanyDataCacheModel.MIDUPCOMPANY = getMIDUPCOMPANY();

		String MIDUPCOMPANY = astraPdca_CompanyDataCacheModel.MIDUPCOMPANY;

		if ((MIDUPCOMPANY != null) && (MIDUPCOMPANY.length() == 0)) {
			astraPdca_CompanyDataCacheModel.MIDUPCOMPANY = null;
		}

		astraPdca_CompanyDataCacheModel.MIDBOTTOM = getMIDBOTTOM();

		String MIDBOTTOM = astraPdca_CompanyDataCacheModel.MIDBOTTOM;

		if ((MIDBOTTOM != null) && (MIDBOTTOM.length() == 0)) {
			astraPdca_CompanyDataCacheModel.MIDBOTTOM = null;
		}

		astraPdca_CompanyDataCacheModel.MIDBOTTOMTITLE = getMIDBOTTOMTITLE();

		String MIDBOTTOMTITLE = astraPdca_CompanyDataCacheModel.MIDBOTTOMTITLE;

		if ((MIDBOTTOMTITLE != null) && (MIDBOTTOMTITLE.length() == 0)) {
			astraPdca_CompanyDataCacheModel.MIDBOTTOMTITLE = null;
		}

		astraPdca_CompanyDataCacheModel.MIDBOTTOMCOMPANY = getMIDBOTTOMCOMPANY();

		String MIDBOTTOMCOMPANY = astraPdca_CompanyDataCacheModel.MIDBOTTOMCOMPANY;

		if ((MIDBOTTOMCOMPANY != null) && (MIDBOTTOMCOMPANY.length() == 0)) {
			astraPdca_CompanyDataCacheModel.MIDBOTTOMCOMPANY = null;
		}

		astraPdca_CompanyDataCacheModel.RIGHTUP = getRIGHTUP();

		String RIGHTUP = astraPdca_CompanyDataCacheModel.RIGHTUP;

		if ((RIGHTUP != null) && (RIGHTUP.length() == 0)) {
			astraPdca_CompanyDataCacheModel.RIGHTUP = null;
		}

		astraPdca_CompanyDataCacheModel.RIGHTUPTITLE = getRIGHTUPTITLE();

		String RIGHTUPTITLE = astraPdca_CompanyDataCacheModel.RIGHTUPTITLE;

		if ((RIGHTUPTITLE != null) && (RIGHTUPTITLE.length() == 0)) {
			astraPdca_CompanyDataCacheModel.RIGHTUPTITLE = null;
		}

		astraPdca_CompanyDataCacheModel.RIGHTUPCOMPANY = getRIGHTUPCOMPANY();

		String RIGHTUPCOMPANY = astraPdca_CompanyDataCacheModel.RIGHTUPCOMPANY;

		if ((RIGHTUPCOMPANY != null) && (RIGHTUPCOMPANY.length() == 0)) {
			astraPdca_CompanyDataCacheModel.RIGHTUPCOMPANY = null;
		}

		astraPdca_CompanyDataCacheModel.RIGHTBOTTOM = getRIGHTBOTTOM();

		String RIGHTBOTTOM = astraPdca_CompanyDataCacheModel.RIGHTBOTTOM;

		if ((RIGHTBOTTOM != null) && (RIGHTBOTTOM.length() == 0)) {
			astraPdca_CompanyDataCacheModel.RIGHTBOTTOM = null;
		}

		astraPdca_CompanyDataCacheModel.RIGHTBOTTOMTITLE = getRIGHTBOTTOMTITLE();

		String RIGHTBOTTOMTITLE = astraPdca_CompanyDataCacheModel.RIGHTBOTTOMTITLE;

		if ((RIGHTBOTTOMTITLE != null) && (RIGHTBOTTOMTITLE.length() == 0)) {
			astraPdca_CompanyDataCacheModel.RIGHTBOTTOMTITLE = null;
		}

		astraPdca_CompanyDataCacheModel.RIGHTBOTTOMCOMPANY = getRIGHTBOTTOMCOMPANY();

		String RIGHTBOTTOMCOMPANY = astraPdca_CompanyDataCacheModel.RIGHTBOTTOMCOMPANY;

		if ((RIGHTBOTTOMCOMPANY != null) && (RIGHTBOTTOMCOMPANY.length() == 0)) {
			astraPdca_CompanyDataCacheModel.RIGHTBOTTOMCOMPANY = null;
		}

		astraPdca_CompanyDataCacheModel.ModuleId = getModuleId();

		astraPdca_CompanyDataCacheModel.YearId = getYearId();

		astraPdca_CompanyDataCacheModel.CheckFlag = getCheckFlag();

		String CheckFlag = astraPdca_CompanyDataCacheModel.CheckFlag;

		if ((CheckFlag != null) && (CheckFlag.length() == 0)) {
			astraPdca_CompanyDataCacheModel.CheckFlag = null;
		}

		astraPdca_CompanyDataCacheModel.SiteId = getSiteId();

		Date CreateDate = getCreateDate();

		if (CreateDate != null) {
			astraPdca_CompanyDataCacheModel.CreateDate = CreateDate.getTime();
		}
		else {
			astraPdca_CompanyDataCacheModel.CreateDate = Long.MIN_VALUE;
		}

		astraPdca_CompanyDataCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = astraPdca_CompanyDataCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			astraPdca_CompanyDataCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			astraPdca_CompanyDataCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			astraPdca_CompanyDataCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		astraPdca_CompanyDataCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = astraPdca_CompanyDataCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			astraPdca_CompanyDataCacheModel.ModifiedBy = null;
		}

		return astraPdca_CompanyDataCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(65);

		sb.append("{companyId=");
		sb.append(getCompanyId());
		sb.append(", CompanyCode=");
		sb.append(getCompanyCode());
		sb.append(", CompanyName=");
		sb.append(getCompanyName());
		sb.append(", GroupName=");
		sb.append(getGroupName());
		sb.append(", DIC=");
		sb.append(getDIC());
		sb.append(", DICINITIAL=");
		sb.append(getDICINITIAL());
		sb.append(", LEFTUP=");
		sb.append(getLEFTUP());
		sb.append(", LEFTUPTITLE=");
		sb.append(getLEFTUPTITLE());
		sb.append(", LEFTUPCOMPANY=");
		sb.append(getLEFTUPCOMPANY());
		sb.append(", LEFTBOTTOM=");
		sb.append(getLEFTBOTTOM());
		sb.append(", LEFTBOTTOMTITLE=");
		sb.append(getLEFTBOTTOMTITLE());
		sb.append(", LEFTBOTTOMCOMPANY=");
		sb.append(getLEFTBOTTOMCOMPANY());
		sb.append(", MIDUP=");
		sb.append(getMIDUP());
		sb.append(", MIDUPTITLE=");
		sb.append(getMIDUPTITLE());
		sb.append(", MIDUPCOMPANY=");
		sb.append(getMIDUPCOMPANY());
		sb.append(", MIDBOTTOM=");
		sb.append(getMIDBOTTOM());
		sb.append(", MIDBOTTOMTITLE=");
		sb.append(getMIDBOTTOMTITLE());
		sb.append(", MIDBOTTOMCOMPANY=");
		sb.append(getMIDBOTTOMCOMPANY());
		sb.append(", RIGHTUP=");
		sb.append(getRIGHTUP());
		sb.append(", RIGHTUPTITLE=");
		sb.append(getRIGHTUPTITLE());
		sb.append(", RIGHTUPCOMPANY=");
		sb.append(getRIGHTUPCOMPANY());
		sb.append(", RIGHTBOTTOM=");
		sb.append(getRIGHTBOTTOM());
		sb.append(", RIGHTBOTTOMTITLE=");
		sb.append(getRIGHTBOTTOMTITLE());
		sb.append(", RIGHTBOTTOMCOMPANY=");
		sb.append(getRIGHTBOTTOMCOMPANY());
		sb.append(", ModuleId=");
		sb.append(getModuleId());
		sb.append(", YearId=");
		sb.append(getYearId());
		sb.append(", CheckFlag=");
		sb.append(getCheckFlag());
		sb.append(", SiteId=");
		sb.append(getSiteId());
		sb.append(", CreateDate=");
		sb.append(getCreateDate());
		sb.append(", CreatedBy=");
		sb.append(getCreatedBy());
		sb.append(", ModifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", ModifiedBy=");
		sb.append(getModifiedBy());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(100);

		sb.append("<model><model-name>");
		sb.append("com.astra.anblicks.pdca.model.AstraPdca_CompanyData");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CompanyCode</column-name><column-value><![CDATA[");
		sb.append(getCompanyCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CompanyName</column-name><column-value><![CDATA[");
		sb.append(getCompanyName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>GroupName</column-name><column-value><![CDATA[");
		sb.append(getGroupName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DIC</column-name><column-value><![CDATA[");
		sb.append(getDIC());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>DICINITIAL</column-name><column-value><![CDATA[");
		sb.append(getDICINITIAL());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>LEFTUP</column-name><column-value><![CDATA[");
		sb.append(getLEFTUP());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>LEFTUPTITLE</column-name><column-value><![CDATA[");
		sb.append(getLEFTUPTITLE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>LEFTUPCOMPANY</column-name><column-value><![CDATA[");
		sb.append(getLEFTUPCOMPANY());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>LEFTBOTTOM</column-name><column-value><![CDATA[");
		sb.append(getLEFTBOTTOM());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>LEFTBOTTOMTITLE</column-name><column-value><![CDATA[");
		sb.append(getLEFTBOTTOMTITLE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>LEFTBOTTOMCOMPANY</column-name><column-value><![CDATA[");
		sb.append(getLEFTBOTTOMCOMPANY());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MIDUP</column-name><column-value><![CDATA[");
		sb.append(getMIDUP());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MIDUPTITLE</column-name><column-value><![CDATA[");
		sb.append(getMIDUPTITLE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MIDUPCOMPANY</column-name><column-value><![CDATA[");
		sb.append(getMIDUPCOMPANY());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MIDBOTTOM</column-name><column-value><![CDATA[");
		sb.append(getMIDBOTTOM());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MIDBOTTOMTITLE</column-name><column-value><![CDATA[");
		sb.append(getMIDBOTTOMTITLE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>MIDBOTTOMCOMPANY</column-name><column-value><![CDATA[");
		sb.append(getMIDBOTTOMCOMPANY());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>RIGHTUP</column-name><column-value><![CDATA[");
		sb.append(getRIGHTUP());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>RIGHTUPTITLE</column-name><column-value><![CDATA[");
		sb.append(getRIGHTUPTITLE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>RIGHTUPCOMPANY</column-name><column-value><![CDATA[");
		sb.append(getRIGHTUPCOMPANY());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>RIGHTBOTTOM</column-name><column-value><![CDATA[");
		sb.append(getRIGHTBOTTOM());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>RIGHTBOTTOMTITLE</column-name><column-value><![CDATA[");
		sb.append(getRIGHTBOTTOMTITLE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>RIGHTBOTTOMCOMPANY</column-name><column-value><![CDATA[");
		sb.append(getRIGHTBOTTOMCOMPANY());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ModuleId</column-name><column-value><![CDATA[");
		sb.append(getModuleId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>YearId</column-name><column-value><![CDATA[");
		sb.append(getYearId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CheckFlag</column-name><column-value><![CDATA[");
		sb.append(getCheckFlag());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SiteId</column-name><column-value><![CDATA[");
		sb.append(getSiteId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CreateDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CreatedBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ModifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ModifiedBy</column-name><column-value><![CDATA[");
		sb.append(getModifiedBy());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = AstraPdca_CompanyData.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			AstraPdca_CompanyData.class
		};
	private long _companyId;
	private String _CompanyCode;
	private String _CompanyName;
	private String _GroupName;
	private String _DIC;
	private String _DICINITIAL;
	private String _LEFTUP;
	private String _LEFTUPTITLE;
	private String _LEFTUPCOMPANY;
	private String _LEFTBOTTOM;
	private String _LEFTBOTTOMTITLE;
	private String _LEFTBOTTOMCOMPANY;
	private String _MIDUP;
	private String _MIDUPTITLE;
	private String _MIDUPCOMPANY;
	private String _MIDBOTTOM;
	private String _MIDBOTTOMTITLE;
	private String _MIDBOTTOMCOMPANY;
	private String _RIGHTUP;
	private String _RIGHTUPTITLE;
	private String _RIGHTUPCOMPANY;
	private String _RIGHTBOTTOM;
	private String _RIGHTBOTTOMTITLE;
	private String _RIGHTBOTTOMCOMPANY;
	private long _ModuleId;
	private long _YearId;
	private String _CheckFlag;
	private long _SiteId;
	private Date _CreateDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;
	private AstraPdca_CompanyData _escapedModel;
}