/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.anblicks.pdca.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.astra.anblicks.pdca.model.AstraPdca_CompanyData;
import com.astra.anblicks.pdca.service.AstraPdca_CompanyDataLocalServiceUtil;

/**
 * The extended model base implementation for the AstraPdca_CompanyData service. Represents a row in the &quot;pdca_astrapdca_companydata&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AstraPdca_CompanyDataImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AstraPdca_CompanyDataImpl
 * @see AstraPdca_CompanyData
 * @generated
 */
@ProviderType
public abstract class AstraPdca_CompanyDataBaseImpl
	extends AstraPdca_CompanyDataModelImpl implements AstraPdca_CompanyData {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a astra pdca_ company data model instance should use the {@link AstraPdca_CompanyData} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			AstraPdca_CompanyDataLocalServiceUtil.addAstraPdca_CompanyData(this);
		}
		else {
			AstraPdca_CompanyDataLocalServiceUtil.updateAstraPdca_CompanyData(this);
		}
	}
}