/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.anblicks.pdca.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.astra.anblicks.pdca.model.AstraPdca_Module;
import com.astra.anblicks.pdca.model.AstraPdca_ModuleModel;
import com.astra.anblicks.pdca.model.AstraPdca_ModuleSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the AstraPdca_Module service. Represents a row in the &quot;pdca_astrapdca_module&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link AstraPdca_ModuleModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AstraPdca_ModuleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AstraPdca_ModuleImpl
 * @see AstraPdca_Module
 * @see AstraPdca_ModuleModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class AstraPdca_ModuleModelImpl extends BaseModelImpl<AstraPdca_Module>
	implements AstraPdca_ModuleModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a astra pdca_ module model instance should use the {@link AstraPdca_Module} interface instead.
	 */
	public static final String TABLE_NAME = "pdca_astrapdca_module";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ModuleId", Types.BIGINT },
			{ "ModuleId_Company", Types.BIGINT },
			{ "ModuleName", Types.VARCHAR },
			{ "checkUncheckFlag", Types.VARCHAR },
			{ "SiteId", Types.BIGINT },
			{ "CreateDate", Types.TIMESTAMP },
			{ "CreatedBy", Types.VARCHAR },
			{ "ModifiedDate", Types.TIMESTAMP },
			{ "ModifiedBy", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("ModuleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ModuleId_Company", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ModuleName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("checkUncheckFlag", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("SiteId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("CreateDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table pdca_astrapdca_module (ModuleId LONG not null primary key,ModuleId_Company LONG,ModuleName VARCHAR(75) null,checkUncheckFlag VARCHAR(75) null,SiteId LONG,CreateDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table pdca_astrapdca_module";
	public static final String ORDER_BY_JPQL = " ORDER BY astraPdca_Module.ModuleId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY pdca_astrapdca_module.ModuleId ASC";
	public static final String DATA_SOURCE = "pdcaSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.astra.anblicks.pdca.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.astra.anblicks.pdca.model.AstraPdca_Module"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.astra.anblicks.pdca.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.astra.anblicks.pdca.model.AstraPdca_Module"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static AstraPdca_Module toModel(AstraPdca_ModuleSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		AstraPdca_Module model = new AstraPdca_ModuleImpl();

		model.setModuleId(soapModel.getModuleId());
		model.setModuleId_Company(soapModel.getModuleId_Company());
		model.setModuleName(soapModel.getModuleName());
		model.setCheckUncheckFlag(soapModel.getCheckUncheckFlag());
		model.setSiteId(soapModel.getSiteId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setCreatedBy(soapModel.getCreatedBy());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setModifiedBy(soapModel.getModifiedBy());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<AstraPdca_Module> toModels(
		AstraPdca_ModuleSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<AstraPdca_Module> models = new ArrayList<AstraPdca_Module>(soapModels.length);

		for (AstraPdca_ModuleSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.astra.anblicks.pdca.service.util.ServiceProps.get(
				"lock.expiration.time.com.astra.anblicks.pdca.model.AstraPdca_Module"));

	public AstraPdca_ModuleModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ModuleId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setModuleId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ModuleId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AstraPdca_Module.class;
	}

	@Override
	public String getModelClassName() {
		return AstraPdca_Module.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("ModuleId", getModuleId());
		attributes.put("ModuleId_Company", getModuleId_Company());
		attributes.put("ModuleName", getModuleName());
		attributes.put("checkUncheckFlag", getCheckUncheckFlag());
		attributes.put("SiteId", getSiteId());
		attributes.put("CreateDate", getCreateDate());
		attributes.put("CreatedBy", getCreatedBy());
		attributes.put("ModifiedDate", getModifiedDate());
		attributes.put("ModifiedBy", getModifiedBy());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long ModuleId = (Long)attributes.get("ModuleId");

		if (ModuleId != null) {
			setModuleId(ModuleId);
		}

		Long ModuleId_Company = (Long)attributes.get("ModuleId_Company");

		if (ModuleId_Company != null) {
			setModuleId_Company(ModuleId_Company);
		}

		String ModuleName = (String)attributes.get("ModuleName");

		if (ModuleName != null) {
			setModuleName(ModuleName);
		}

		String checkUncheckFlag = (String)attributes.get("checkUncheckFlag");

		if (checkUncheckFlag != null) {
			setCheckUncheckFlag(checkUncheckFlag);
		}

		Long SiteId = (Long)attributes.get("SiteId");

		if (SiteId != null) {
			setSiteId(SiteId);
		}

		Date CreateDate = (Date)attributes.get("CreateDate");

		if (CreateDate != null) {
			setCreateDate(CreateDate);
		}

		String CreatedBy = (String)attributes.get("CreatedBy");

		if (CreatedBy != null) {
			setCreatedBy(CreatedBy);
		}

		Date ModifiedDate = (Date)attributes.get("ModifiedDate");

		if (ModifiedDate != null) {
			setModifiedDate(ModifiedDate);
		}

		String ModifiedBy = (String)attributes.get("ModifiedBy");

		if (ModifiedBy != null) {
			setModifiedBy(ModifiedBy);
		}
	}

	@JSON
	@Override
	public long getModuleId() {
		return _ModuleId;
	}

	@Override
	public void setModuleId(long ModuleId) {
		_ModuleId = ModuleId;
	}

	@JSON
	@Override
	public long getModuleId_Company() {
		return _ModuleId_Company;
	}

	@Override
	public void setModuleId_Company(long ModuleId_Company) {
		_ModuleId_Company = ModuleId_Company;
	}

	@JSON
	@Override
	public String getModuleName() {
		if (_ModuleName == null) {
			return StringPool.BLANK;
		}
		else {
			return _ModuleName;
		}
	}

	@Override
	public void setModuleName(String ModuleName) {
		_ModuleName = ModuleName;
	}

	@JSON
	@Override
	public String getCheckUncheckFlag() {
		if (_checkUncheckFlag == null) {
			return StringPool.BLANK;
		}
		else {
			return _checkUncheckFlag;
		}
	}

	@Override
	public void setCheckUncheckFlag(String checkUncheckFlag) {
		_checkUncheckFlag = checkUncheckFlag;
	}

	@JSON
	@Override
	public long getSiteId() {
		return _SiteId;
	}

	@Override
	public void setSiteId(long SiteId) {
		_SiteId = SiteId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _CreateDate;
	}

	@Override
	public void setCreateDate(Date CreateDate) {
		_CreateDate = CreateDate;
	}

	@JSON
	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		_CreatedBy = CreatedBy;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		_ModifiedDate = ModifiedDate;
	}

	@JSON
	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		_ModifiedBy = ModifiedBy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			AstraPdca_Module.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AstraPdca_Module toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (AstraPdca_Module)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AstraPdca_ModuleImpl astraPdca_ModuleImpl = new AstraPdca_ModuleImpl();

		astraPdca_ModuleImpl.setModuleId(getModuleId());
		astraPdca_ModuleImpl.setModuleId_Company(getModuleId_Company());
		astraPdca_ModuleImpl.setModuleName(getModuleName());
		astraPdca_ModuleImpl.setCheckUncheckFlag(getCheckUncheckFlag());
		astraPdca_ModuleImpl.setSiteId(getSiteId());
		astraPdca_ModuleImpl.setCreateDate(getCreateDate());
		astraPdca_ModuleImpl.setCreatedBy(getCreatedBy());
		astraPdca_ModuleImpl.setModifiedDate(getModifiedDate());
		astraPdca_ModuleImpl.setModifiedBy(getModifiedBy());

		astraPdca_ModuleImpl.resetOriginalValues();

		return astraPdca_ModuleImpl;
	}

	@Override
	public int compareTo(AstraPdca_Module astraPdca_Module) {
		long primaryKey = astraPdca_Module.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AstraPdca_Module)) {
			return false;
		}

		AstraPdca_Module astraPdca_Module = (AstraPdca_Module)obj;

		long primaryKey = astraPdca_Module.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<AstraPdca_Module> toCacheModel() {
		AstraPdca_ModuleCacheModel astraPdca_ModuleCacheModel = new AstraPdca_ModuleCacheModel();

		astraPdca_ModuleCacheModel.ModuleId = getModuleId();

		astraPdca_ModuleCacheModel.ModuleId_Company = getModuleId_Company();

		astraPdca_ModuleCacheModel.ModuleName = getModuleName();

		String ModuleName = astraPdca_ModuleCacheModel.ModuleName;

		if ((ModuleName != null) && (ModuleName.length() == 0)) {
			astraPdca_ModuleCacheModel.ModuleName = null;
		}

		astraPdca_ModuleCacheModel.checkUncheckFlag = getCheckUncheckFlag();

		String checkUncheckFlag = astraPdca_ModuleCacheModel.checkUncheckFlag;

		if ((checkUncheckFlag != null) && (checkUncheckFlag.length() == 0)) {
			astraPdca_ModuleCacheModel.checkUncheckFlag = null;
		}

		astraPdca_ModuleCacheModel.SiteId = getSiteId();

		Date CreateDate = getCreateDate();

		if (CreateDate != null) {
			astraPdca_ModuleCacheModel.CreateDate = CreateDate.getTime();
		}
		else {
			astraPdca_ModuleCacheModel.CreateDate = Long.MIN_VALUE;
		}

		astraPdca_ModuleCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = astraPdca_ModuleCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			astraPdca_ModuleCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			astraPdca_ModuleCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			astraPdca_ModuleCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		astraPdca_ModuleCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = astraPdca_ModuleCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			astraPdca_ModuleCacheModel.ModifiedBy = null;
		}

		return astraPdca_ModuleCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{ModuleId=");
		sb.append(getModuleId());
		sb.append(", ModuleId_Company=");
		sb.append(getModuleId_Company());
		sb.append(", ModuleName=");
		sb.append(getModuleName());
		sb.append(", checkUncheckFlag=");
		sb.append(getCheckUncheckFlag());
		sb.append(", SiteId=");
		sb.append(getSiteId());
		sb.append(", CreateDate=");
		sb.append(getCreateDate());
		sb.append(", CreatedBy=");
		sb.append(getCreatedBy());
		sb.append(", ModifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", ModifiedBy=");
		sb.append(getModifiedBy());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.astra.anblicks.pdca.model.AstraPdca_Module");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>ModuleId</column-name><column-value><![CDATA[");
		sb.append(getModuleId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ModuleId_Company</column-name><column-value><![CDATA[");
		sb.append(getModuleId_Company());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ModuleName</column-name><column-value><![CDATA[");
		sb.append(getModuleName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>checkUncheckFlag</column-name><column-value><![CDATA[");
		sb.append(getCheckUncheckFlag());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SiteId</column-name><column-value><![CDATA[");
		sb.append(getSiteId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CreateDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CreatedBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ModifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ModifiedBy</column-name><column-value><![CDATA[");
		sb.append(getModifiedBy());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = AstraPdca_Module.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			AstraPdca_Module.class
		};
	private long _ModuleId;
	private long _ModuleId_Company;
	private String _ModuleName;
	private String _checkUncheckFlag;
	private long _SiteId;
	private Date _CreateDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;
	private AstraPdca_Module _escapedModel;
}