/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.anblicks.pdca.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.astra.anblicks.pdca.model.company_user;
import com.astra.anblicks.pdca.service.company_userLocalServiceUtil;

/**
 * The extended model base implementation for the company_user service. Represents a row in the &quot;pdca_company_user&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link company_userImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see company_userImpl
 * @see company_user
 * @generated
 */
@ProviderType
public abstract class company_userBaseImpl extends company_userModelImpl
	implements company_user {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a company_user model instance should use the {@link company_user} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			company_userLocalServiceUtil.addcompany_user(this);
		}
		else {
			company_userLocalServiceUtil.updatecompany_user(this);
		}
	}
}