/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.anblicks.pdca.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.astra.anblicks.pdca.model.pdca_AdminSettings;
import com.astra.anblicks.pdca.model.pdca_AdminSettingsModel;
import com.astra.anblicks.pdca.model.pdca_AdminSettingsSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the pdca_AdminSettings service. Represents a row in the &quot;pdca_pdca_adminsettings&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link pdca_AdminSettingsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link pdca_AdminSettingsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see pdca_AdminSettingsImpl
 * @see pdca_AdminSettings
 * @see pdca_AdminSettingsModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class pdca_AdminSettingsModelImpl extends BaseModelImpl<pdca_AdminSettings>
	implements pdca_AdminSettingsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a pdca_ admin settings model instance should use the {@link pdca_AdminSettings} interface instead.
	 */
	public static final String TABLE_NAME = "pdca_pdca_adminsettings";
	public static final Object[][] TABLE_COLUMNS = {
			{ "settings_Id", Types.BIGINT },
			{ "moduleId", Types.BIGINT },
			{ "year", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "periodId", Types.BIGINT },
			{ "SiteId", Types.BIGINT },
			{ "CreateDate", Types.TIMESTAMP },
			{ "CreatedBy", Types.VARCHAR },
			{ "ModifiedDate", Types.TIMESTAMP },
			{ "ModifiedBy", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("settings_Id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("moduleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("year", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("periodId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("SiteId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("CreateDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CreatedBy", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ModifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ModifiedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table pdca_pdca_adminsettings (settings_Id LONG not null primary key,moduleId LONG,year LONG,companyId LONG,periodId LONG,SiteId LONG,CreateDate DATE null,CreatedBy VARCHAR(75) null,ModifiedDate DATE null,ModifiedBy VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table pdca_pdca_adminsettings";
	public static final String ORDER_BY_JPQL = " ORDER BY pdca_AdminSettings.settings_Id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY pdca_pdca_adminsettings.settings_Id ASC";
	public static final String DATA_SOURCE = "pdcaSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.astra.anblicks.pdca.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.astra.anblicks.pdca.model.pdca_AdminSettings"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.astra.anblicks.pdca.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.astra.anblicks.pdca.model.pdca_AdminSettings"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static pdca_AdminSettings toModel(pdca_AdminSettingsSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		pdca_AdminSettings model = new pdca_AdminSettingsImpl();

		model.setSettings_Id(soapModel.getSettings_Id());
		model.setModuleId(soapModel.getModuleId());
		model.setYear(soapModel.getYear());
		model.setCompanyId(soapModel.getCompanyId());
		model.setPeriodId(soapModel.getPeriodId());
		model.setSiteId(soapModel.getSiteId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setCreatedBy(soapModel.getCreatedBy());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setModifiedBy(soapModel.getModifiedBy());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<pdca_AdminSettings> toModels(
		pdca_AdminSettingsSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<pdca_AdminSettings> models = new ArrayList<pdca_AdminSettings>(soapModels.length);

		for (pdca_AdminSettingsSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.astra.anblicks.pdca.service.util.ServiceProps.get(
				"lock.expiration.time.com.astra.anblicks.pdca.model.pdca_AdminSettings"));

	public pdca_AdminSettingsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _settings_Id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSettings_Id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _settings_Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return pdca_AdminSettings.class;
	}

	@Override
	public String getModelClassName() {
		return pdca_AdminSettings.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("settings_Id", getSettings_Id());
		attributes.put("moduleId", getModuleId());
		attributes.put("year", getYear());
		attributes.put("companyId", getCompanyId());
		attributes.put("periodId", getPeriodId());
		attributes.put("SiteId", getSiteId());
		attributes.put("CreateDate", getCreateDate());
		attributes.put("CreatedBy", getCreatedBy());
		attributes.put("ModifiedDate", getModifiedDate());
		attributes.put("ModifiedBy", getModifiedBy());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long settings_Id = (Long)attributes.get("settings_Id");

		if (settings_Id != null) {
			setSettings_Id(settings_Id);
		}

		Long moduleId = (Long)attributes.get("moduleId");

		if (moduleId != null) {
			setModuleId(moduleId);
		}

		Long year = (Long)attributes.get("year");

		if (year != null) {
			setYear(year);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long periodId = (Long)attributes.get("periodId");

		if (periodId != null) {
			setPeriodId(periodId);
		}

		Long SiteId = (Long)attributes.get("SiteId");

		if (SiteId != null) {
			setSiteId(SiteId);
		}

		Date CreateDate = (Date)attributes.get("CreateDate");

		if (CreateDate != null) {
			setCreateDate(CreateDate);
		}

		String CreatedBy = (String)attributes.get("CreatedBy");

		if (CreatedBy != null) {
			setCreatedBy(CreatedBy);
		}

		Date ModifiedDate = (Date)attributes.get("ModifiedDate");

		if (ModifiedDate != null) {
			setModifiedDate(ModifiedDate);
		}

		String ModifiedBy = (String)attributes.get("ModifiedBy");

		if (ModifiedBy != null) {
			setModifiedBy(ModifiedBy);
		}
	}

	@JSON
	@Override
	public long getSettings_Id() {
		return _settings_Id;
	}

	@Override
	public void setSettings_Id(long settings_Id) {
		_settings_Id = settings_Id;
	}

	@JSON
	@Override
	public long getModuleId() {
		return _moduleId;
	}

	@Override
	public void setModuleId(long moduleId) {
		_moduleId = moduleId;
	}

	@JSON
	@Override
	public long getYear() {
		return _year;
	}

	@Override
	public void setYear(long year) {
		_year = year;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getPeriodId() {
		return _periodId;
	}

	@Override
	public void setPeriodId(long periodId) {
		_periodId = periodId;
	}

	@JSON
	@Override
	public long getSiteId() {
		return _SiteId;
	}

	@Override
	public void setSiteId(long SiteId) {
		_SiteId = SiteId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _CreateDate;
	}

	@Override
	public void setCreateDate(Date CreateDate) {
		_CreateDate = CreateDate;
	}

	@JSON
	@Override
	public String getCreatedBy() {
		if (_CreatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _CreatedBy;
		}
	}

	@Override
	public void setCreatedBy(String CreatedBy) {
		_CreatedBy = CreatedBy;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _ModifiedDate;
	}

	@Override
	public void setModifiedDate(Date ModifiedDate) {
		_ModifiedDate = ModifiedDate;
	}

	@JSON
	@Override
	public String getModifiedBy() {
		if (_ModifiedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _ModifiedBy;
		}
	}

	@Override
	public void setModifiedBy(String ModifiedBy) {
		_ModifiedBy = ModifiedBy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			pdca_AdminSettings.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public pdca_AdminSettings toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (pdca_AdminSettings)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		pdca_AdminSettingsImpl pdca_AdminSettingsImpl = new pdca_AdminSettingsImpl();

		pdca_AdminSettingsImpl.setSettings_Id(getSettings_Id());
		pdca_AdminSettingsImpl.setModuleId(getModuleId());
		pdca_AdminSettingsImpl.setYear(getYear());
		pdca_AdminSettingsImpl.setCompanyId(getCompanyId());
		pdca_AdminSettingsImpl.setPeriodId(getPeriodId());
		pdca_AdminSettingsImpl.setSiteId(getSiteId());
		pdca_AdminSettingsImpl.setCreateDate(getCreateDate());
		pdca_AdminSettingsImpl.setCreatedBy(getCreatedBy());
		pdca_AdminSettingsImpl.setModifiedDate(getModifiedDate());
		pdca_AdminSettingsImpl.setModifiedBy(getModifiedBy());

		pdca_AdminSettingsImpl.resetOriginalValues();

		return pdca_AdminSettingsImpl;
	}

	@Override
	public int compareTo(pdca_AdminSettings pdca_AdminSettings) {
		long primaryKey = pdca_AdminSettings.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof pdca_AdminSettings)) {
			return false;
		}

		pdca_AdminSettings pdca_AdminSettings = (pdca_AdminSettings)obj;

		long primaryKey = pdca_AdminSettings.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<pdca_AdminSettings> toCacheModel() {
		pdca_AdminSettingsCacheModel pdca_AdminSettingsCacheModel = new pdca_AdminSettingsCacheModel();

		pdca_AdminSettingsCacheModel.settings_Id = getSettings_Id();

		pdca_AdminSettingsCacheModel.moduleId = getModuleId();

		pdca_AdminSettingsCacheModel.year = getYear();

		pdca_AdminSettingsCacheModel.companyId = getCompanyId();

		pdca_AdminSettingsCacheModel.periodId = getPeriodId();

		pdca_AdminSettingsCacheModel.SiteId = getSiteId();

		Date CreateDate = getCreateDate();

		if (CreateDate != null) {
			pdca_AdminSettingsCacheModel.CreateDate = CreateDate.getTime();
		}
		else {
			pdca_AdminSettingsCacheModel.CreateDate = Long.MIN_VALUE;
		}

		pdca_AdminSettingsCacheModel.CreatedBy = getCreatedBy();

		String CreatedBy = pdca_AdminSettingsCacheModel.CreatedBy;

		if ((CreatedBy != null) && (CreatedBy.length() == 0)) {
			pdca_AdminSettingsCacheModel.CreatedBy = null;
		}

		Date ModifiedDate = getModifiedDate();

		if (ModifiedDate != null) {
			pdca_AdminSettingsCacheModel.ModifiedDate = ModifiedDate.getTime();
		}
		else {
			pdca_AdminSettingsCacheModel.ModifiedDate = Long.MIN_VALUE;
		}

		pdca_AdminSettingsCacheModel.ModifiedBy = getModifiedBy();

		String ModifiedBy = pdca_AdminSettingsCacheModel.ModifiedBy;

		if ((ModifiedBy != null) && (ModifiedBy.length() == 0)) {
			pdca_AdminSettingsCacheModel.ModifiedBy = null;
		}

		return pdca_AdminSettingsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{settings_Id=");
		sb.append(getSettings_Id());
		sb.append(", moduleId=");
		sb.append(getModuleId());
		sb.append(", year=");
		sb.append(getYear());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", periodId=");
		sb.append(getPeriodId());
		sb.append(", SiteId=");
		sb.append(getSiteId());
		sb.append(", CreateDate=");
		sb.append(getCreateDate());
		sb.append(", CreatedBy=");
		sb.append(getCreatedBy());
		sb.append(", ModifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", ModifiedBy=");
		sb.append(getModifiedBy());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.astra.anblicks.pdca.model.pdca_AdminSettings");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>settings_Id</column-name><column-value><![CDATA[");
		sb.append(getSettings_Id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>moduleId</column-name><column-value><![CDATA[");
		sb.append(getModuleId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>year</column-name><column-value><![CDATA[");
		sb.append(getYear());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>periodId</column-name><column-value><![CDATA[");
		sb.append(getPeriodId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SiteId</column-name><column-value><![CDATA[");
		sb.append(getSiteId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CreateDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CreatedBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ModifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ModifiedBy</column-name><column-value><![CDATA[");
		sb.append(getModifiedBy());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = pdca_AdminSettings.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			pdca_AdminSettings.class
		};
	private long _settings_Id;
	private long _moduleId;
	private long _year;
	private long _companyId;
	private long _periodId;
	private long _SiteId;
	private Date _CreateDate;
	private String _CreatedBy;
	private Date _ModifiedDate;
	private String _ModifiedBy;
	private pdca_AdminSettings _escapedModel;
}