/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.anblicks.pdca.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the achivementFormula service. Represents a row in the &quot;pdca_achivementFormula&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.astra.anblicks.pdca.model.impl.achivementFormulaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.astra.anblicks.pdca.model.impl.achivementFormulaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see achivementFormula
 * @see com.astra.anblicks.pdca.model.impl.achivementFormulaImpl
 * @see com.astra.anblicks.pdca.model.impl.achivementFormulaModelImpl
 * @generated
 */
@ProviderType
public interface achivementFormulaModel extends BaseModel<achivementFormula> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a achivement formula model instance should use the {@link achivementFormula} interface instead.
	 */

	/**
	 * Returns the primary key of this achivement formula.
	 *
	 * @return the primary key of this achivement formula
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this achivement formula.
	 *
	 * @param primaryKey the primary key of this achivement formula
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this achivement formula.
	 *
	 * @return the uuid of this achivement formula
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this achivement formula.
	 *
	 * @param uuid the uuid of this achivement formula
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the achivement formula ID of this achivement formula.
	 *
	 * @return the achivement formula ID of this achivement formula
	 */
	public long getAchivementFormulaId();

	/**
	 * Sets the achivement formula ID of this achivement formula.
	 *
	 * @param achivementFormulaId the achivement formula ID of this achivement formula
	 */
	public void setAchivementFormulaId(long achivementFormulaId);

	/**
	 * Returns the achivement formula of this achivement formula.
	 *
	 * @return the achivement formula of this achivement formula
	 */
	@AutoEscape
	public String getAchivementFormula();

	/**
	 * Sets the achivement formula of this achivement formula.
	 *
	 * @param achivementFormula the achivement formula of this achivement formula
	 */
	public void setAchivementFormula(String achivementFormula);

	/**
	 * Returns the item description ID of this achivement formula.
	 *
	 * @return the item description ID of this achivement formula
	 */
	public long getItemDescriptionId();

	/**
	 * Sets the item description ID of this achivement formula.
	 *
	 * @param itemDescriptionId the item description ID of this achivement formula
	 */
	public void setItemDescriptionId(long itemDescriptionId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.astra.anblicks.pdca.model.achivementFormula achivementFormula);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.astra.anblicks.pdca.model.achivementFormula> toCacheModel();

	@Override
	public com.astra.anblicks.pdca.model.achivementFormula toEscapedModel();

	@Override
	public com.astra.anblicks.pdca.model.achivementFormula toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}