/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.anblicks.pdca.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the cla_kpi service. Represents a row in the &quot;pdca_cla_kpi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.astra.anblicks.pdca.model.impl.cla_kpiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.astra.anblicks.pdca.model.impl.cla_kpiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see cla_kpi
 * @see com.astra.anblicks.pdca.model.impl.cla_kpiImpl
 * @see com.astra.anblicks.pdca.model.impl.cla_kpiModelImpl
 * @generated
 */
@ProviderType
public interface cla_kpiModel extends BaseModel<cla_kpi> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cla_kpi model instance should use the {@link cla_kpi} interface instead.
	 */

	/**
	 * Returns the primary key of this cla_kpi.
	 *
	 * @return the primary key of this cla_kpi
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cla_kpi.
	 *
	 * @param primaryKey the primary key of this cla_kpi
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this cla_kpi.
	 *
	 * @return the uuid of this cla_kpi
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this cla_kpi.
	 *
	 * @param uuid the uuid of this cla_kpi
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the cla kpi ID of this cla_kpi.
	 *
	 * @return the cla kpi ID of this cla_kpi
	 */
	public long getClaKpiId();

	/**
	 * Sets the cla kpi ID of this cla_kpi.
	 *
	 * @param claKpiId the cla kpi ID of this cla_kpi
	 */
	public void setClaKpiId(long claKpiId);

	/**
	 * Returns the kpi ID of this cla_kpi.
	 *
	 * @return the kpi ID of this cla_kpi
	 */
	public long getKpiId();

	/**
	 * Sets the kpi ID of this cla_kpi.
	 *
	 * @param kpiId the kpi ID of this cla_kpi
	 */
	public void setKpiId(long kpiId);

	/**
	 * Returns the period ID of this cla_kpi.
	 *
	 * @return the period ID of this cla_kpi
	 */
	public long getPeriodId();

	/**
	 * Sets the period ID of this cla_kpi.
	 *
	 * @param periodId the period ID of this cla_kpi
	 */
	public void setPeriodId(long periodId);

	/**
	 * Returns the ytd of this cla_kpi.
	 *
	 * @return the ytd of this cla_kpi
	 */
	public long getYtd();

	/**
	 * Sets the ytd of this cla_kpi.
	 *
	 * @param ytd the ytd of this cla_kpi
	 */
	public void setYtd(long ytd);

	/**
	 * Returns the ol of this cla_kpi.
	 *
	 * @return the ol of this cla_kpi
	 */
	public double getOl();

	/**
	 * Sets the ol of this cla_kpi.
	 *
	 * @param ol the ol of this cla_kpi
	 */
	public void setOl(double ol);

	/**
	 * Returns the cla point of this cla_kpi.
	 *
	 * @return the cla point of this cla_kpi
	 */
	public double getClaPoint();

	/**
	 * Sets the cla point of this cla_kpi.
	 *
	 * @param claPoint the cla point of this cla_kpi
	 */
	public void setClaPoint(double claPoint);

	/**
	 * Returns the achivement of this cla_kpi.
	 *
	 * @return the achivement of this cla_kpi
	 */
	public double getAchivement();

	/**
	 * Sets the achivement of this cla_kpi.
	 *
	 * @param achivement the achivement of this cla_kpi
	 */
	public void setAchivement(double achivement);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.astra.anblicks.pdca.model.cla_kpi cla_kpi);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.astra.anblicks.pdca.model.cla_kpi> toCacheModel();

	@Override
	public com.astra.anblicks.pdca.model.cla_kpi toEscapedModel();

	@Override
	public com.astra.anblicks.pdca.model.cla_kpi toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}