/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.astra.anblicks.pdca.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the itemDescription service. Represents a row in the &quot;pdca_itemDescription&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.astra.anblicks.pdca.model.impl.itemDescriptionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.astra.anblicks.pdca.model.impl.itemDescriptionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see itemDescription
 * @see com.astra.anblicks.pdca.model.impl.itemDescriptionImpl
 * @see com.astra.anblicks.pdca.model.impl.itemDescriptionModelImpl
 * @generated
 */
@ProviderType
public interface itemDescriptionModel extends BaseModel<itemDescription> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a item description model instance should use the {@link itemDescription} interface instead.
	 */

	/**
	 * Returns the primary key of this item description.
	 *
	 * @return the primary key of this item description
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this item description.
	 *
	 * @param primaryKey the primary key of this item description
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this item description.
	 *
	 * @return the uuid of this item description
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this item description.
	 *
	 * @param uuid the uuid of this item description
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the item description ID of this item description.
	 *
	 * @return the item description ID of this item description
	 */
	public long getItemDescriptionId();

	/**
	 * Sets the item description ID of this item description.
	 *
	 * @param itemDescriptionId the item description ID of this item description
	 */
	public void setItemDescriptionId(long itemDescriptionId);

	/**
	 * Returns the item description name of this item description.
	 *
	 * @return the item description name of this item description
	 */
	@AutoEscape
	public String getItemDescriptionName();

	/**
	 * Sets the item description name of this item description.
	 *
	 * @param itemDescriptionName the item description name of this item description
	 */
	public void setItemDescriptionName(String itemDescriptionName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.astra.anblicks.pdca.model.itemDescription itemDescription);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.astra.anblicks.pdca.model.itemDescription> toCacheModel();

	@Override
	public com.astra.anblicks.pdca.model.itemDescription toEscapedModel();

	@Override
	public com.astra.anblicks.pdca.model.itemDescription toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}